### ISSUE TITLE
Review requested: kube-bench configuration for microk8s

### ISSUE THREAD

**Issue by mkretz** [ubuntu/microk8s#1001]
Dear microk8s team, 

Would someone of you have time to check the microk8s configuration for [kube-bench](https://github.com/aquasecurity/kube-bench) proposed in [this pull request](https://github.com/aquasecurity/kube-bench/pull/556)?

Specific questions: 
- Have we missed anything important? 
- Are any of the paths referenced in the config subject to change in a future release of microk8s?
- Does it make sense to have rule for microk8s in kube-bench? (in my opinion, it does)

Thanks in advance for your feedback!

**Comment by ktsakalozos** [comment]
Thank you for this PR @mkretz, LGTM already commented on it. Most of the failing checks are trivial to address. Hopefully we will soon get some time to address these issues.

To your questions:
- You haven't missed anything important as far as I can tell.
- The paths used are not going to change in the foreseeable future.
- Having a way to assess the security of a MicroK8s deployment makes sense. 

I am going to close this issue here. You are welcomed to open a new issue requesting us to address the security warnings reported by kube-bench.

**Comment by Bessonov** [comment]
I just want to link this repo here: https://github.com/didier-durand/microk8s-kube-bench
