### ISSUE TITLE
Race condition with microk8s.status

### ISSUE THREAD

**Issue by knkski** [ubuntu/microk8s#1097]
Some more discussion here: https://bugs.launchpad.net/juju/+bug/1871133

Copying over @ktsakalozos's explanation:

Currently `microk8s.status` will report an addon enabled as soon as one representative pod is scheduled. This tells you that k8s
* is running,
* has received your request,
* has resources to host the addon's workload.

The race condition @knkski reports is that we ask for the status of an addon before its workload is scheduled. We could check the existence of the dns deployment and not the scheduled pod (but even that will not be race free). For the needs of juju I suspect storage and dns need to scheduled and running before a bootstrap succeeds. We could check this with a kubectl rollout status on specific deployments.

**Comment by knkski** [comment]
It seems like we could have each `microk8s.enable X` command simply wait until the appropriate resources have come up properly, instead of just creating them and returning. E.g. `microk8s.enable dns` would run `microk8s.kubectl wait -nkube-system --for=condition=available deployment/dns` after creating the deployment. There's an additional question of whether to make that behavior the default or opt-in via a `--wait` flag. I'd be in favor of making it the default behavior, since it's unlikely that anyone's relying on the current behavior, and it's less surprising.

**Comment by ktsakalozos** [comment]
I do not think we can change the default behavior so easily. I do not know how many user scripts will break if we change the default behavior of "microk8s.status" and "microk8s.enable". In addition the audience (k8s users) are familiar with the concept of "tell k8s what to do and return" instead of "tell k8s what to do and wait until it is done". For example kubectl apply, applies the manifests and returns, there is no waiting. I think it comes more natural to microk8s.enable not to wait for the completion of a deployment. Plus, we should not force users to keep a shell open for 20 minutes.

An extra (--wait) flag in the enable script seems reasonable. The challenge here is how to tell if a deployment is really ready. Currently microk8s.status waits for the scheduling of some representative pods before reporting an addon as enabled. If we really want to make sure a complex addon is ready we should be checking all deployments, daemon sets and anything else we see fit. This puts more effort in writing addons and keeping them up to date. Perhaps this is a cost we have to pay.
