### ISSUE TITLE
Security: don't bind to insecure address by default

### ISSUE THREAD

**Issue by tuxcanfly** [ubuntu/microk8s#110]
By default, `microk8s` binds to `0.0.0.0`, which can lead to security issues. `suppoie` is a malware which seems to exploit this. Please consider removing the offending arg `--insecure-bind-address=0.0.0.0`.

**Comment by ktsakalozos** [comment]
Thank you for reporting this @tuxcanfly. We already have a PR that works towards securing microk8s https://github.com/ubuntu/microk8s/pull/88. It should hit the edge channel soon.

**Comment by lmakarov** [comment]
I learned about this project at KuberCon last week and started playing with it on a cloud instance.

The instance [got exploited within hours](http://bit.ly/2R2bwgM)...

Since this project is focused on helping developers and novice users getting started with K8s, it would be good to have some bare minimum security to protect users from the obvious attack vectors with K8s.

**Comment by StephanX** [comment]
Just my two bits, but I'd say the opposite: if users need to secure access to this local development tool, they should learn how to do so.  Anyone who's ever tried to kick the tires on redis knows the pain involved when you use a bind address of (say) 127.0.0.1 instead of 0.0.0.0.

**Comment by Cryptophobia** [comment]
Thank you for the article @lmakarov . I've never tried microk8s but your article is making a great criticism about using `--insecure-bind-address=0.0.0.0` by default.

@StephanX that's not really a good excuse. There are lots of tools out there that don't expose and bind directly to 0.0.0.0 by default. Redis always binds automatically to the local interface by default as defined in redis.conf. With Redis you are dealing with one component which can have a sufficiently large enough password to prevent exploitation from remote attackers given you secure the port. With K8s you are dealing with a whole API layer of multiple components usually connected to dns and networking components, which can have even more attack vectors. 

An experimental tool that is supposed to be used for development and learning k8s should not serve as an attack vector. Especially not to the new users of k8s. Canonical is going around conferences spreading unsecured software and making it easier for new users to get exploited.

There is probably a better way. Probably `--insecure-bind-address=127.0.0.1` for a start.

**Comment by StephanX** [comment]
@cryptophobia - well, username checks out. 

The decision ultimately trades usability for security, as is often the case. The question would be how many issue posts complaining about lack of security become issue posts complaining about usability. It's infinitely easier to point fingers and chide others, than to actually do the work and carry the water.

**Comment by Cryptophobia** [comment]
> @Cryptophobia - well, username checks out.

Don't ridicule my name. People can't pick their names or their parents. My parents named me Cryptophobia for a reason and I can't change that.

> The decision ultimately trades usability for security, as is often the case. The question would be how many issue posts complaining about lack of security become issue posts complaining about usability. 

This trade-off is clearly never outlined in the design documents or documentation. If Canonical is so interested in k8s and making developers lives better with this open source project, then they should at least outline the security risks of running microk8s in any environment or write documentation to secure that environment from the start.

> It's infinitely easier to point fingers and chide others, than to actually do the work and carry the water.
> Instead of wagging fingers, why haven't either of you filed pull requests?

All I'm saying is before marketing people are sent around public conferences hustling products exploited by common malware and asking users to try them, maybe there should be at least better documentation or clearly outlined limitations/security risks. 

Basic security from the start is a basic right for users. That's what I believe. Anything less is arrogant and disrespectful.

All in all, this leads me to the conclusion that this repo is just a product to show off Canonical's snapcraft.io garbage package manager by some [Architecture Astronauts](https://www.joelonsoftware.com/2001/04/21/dont-let-architecture-astronauts-scare-you/). No focus on basic security. Ton of marketing. And adds no value to the open source community.

**Comment by gtrak** [comment]
There's not much reason or benefit of a default 0.0.0.0 bind for software that is intended to be used only for local development.  It's not security vs usability, since the intended use-case is clear.

**Comment by gbevan** [comment]
from the website 
> ... Use it for offline development, prototyping, testing, or **use it on a VM as a small, cheap, reliable k8s for CI/CD. Makes a great k8s for appliances** - develop your IoT apps for k8s and deploy them to MicroK8s on your boxes.

(i added bold) I'd like to use microk8s as an "appliance" (e.g. for CI/CD pipelines for small teams), but I would like it to be secure enough for (internal) production.  That probably means the api binding to 0.0.0.0 but https with certificates for client api connections.  I'd welcome your thoughts?

**Comment by Cryptophobia** [comment]
The default should be secure but also configurable - localhost. Then it should provide the option to bind to 0.0.0.0 or port forward but only at the user's discretion. 

@gbevan You will need something like Kong or Keycloak in front of microk8s so that your developers can auth and https for the client api connections to the backend microk8s.

https://ncarlier.gitbooks.io/oss-api-management/content/howto-kong_with_keycloak.html

**Comment by ktsakalozos** [comment]
Hi,

Thank you all for your input. Those of you who had a bad user experience please accept my appologies.

We all want to have this issue resolved; to do so we need to move forward with PR https://github.com/ubuntu/microk8s/pull/88

Here is what you can do:
 - Review the document https://github.com/ubuntu/microk8s/blob/feature/access/docs/ports.md describing the setup porposed. This doc is part of the PR so you can leave your comments there.
 - A build with the proposed security fixes is available for you to deploy and test. You need to remove your current MicroK8s and then `sudo snap install microk8s --classic  --channel=1.13/edge/security-testing`
 - You can provide a code review on the above PR. Your feedback is much appreciated.

@gbevan I think the proposed patch does exactly what you describe. The API service is available on port `16443` over SSL and users have to present proper credentials.

@gtrak, @Cryptophobia thank you for your input, I would appreciate any feedback you may give on the proposed patch.

@StephanX, thank you for presenting the low-security approach. I totally feel your frustration everytime I fight with the dev tools/frameworks instead of focusing on the problem I have to solve. I would really appreciate if you could deploy MicroK8s from  channel `1.13/edge/security-testing` and let me know if the user experience is much worse.

@lmakarov, thank you for the blog, it was a nice read. The security issues are always a concern. I have to thank you, because by speaking out loud you give us the oportunity to improve MicroK8s.

@cmars, @wallyworld, will this PR affect the UX you expect?

Thank you all for trying out and improving MicroK8s.

**Comment by gbevan** [comment]
@ktsakalozos 

> @gbevan I think the proposed patch does exactly what you describe. The API service is available on port `16443` over SSL and users have to present proper credentials.

I see in PR#88 it is refering to a static password file for 16443 access.  Thats fine for user access, but what about app-2-app? I'd like to be access the api from devops/automation tools like jenkins etc.

**Comment by gbevan** [comment]
I'm using [this gist](https://gist.github.com/gbevan/5e863f1ba90d3e0bc42062ce6bf9b9a7) approach for now - leaving iptables FORWARD rule as DROP and explicitly enabling https on 6443 to the proxy, blocking access to 8080...

**Comment by ktsakalozos** [comment]
> I'd like to be accessing the api from devops/automation tools like jenkins

@gbevan you can edit `/var/snap/microk8s/current/credentials/basic_auth.csv` and add whatever passwords you want.

**Comment by jaredthirsk** [comment]
@StephanX  

Log into linux VM, nice welcome message:
```
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)

...

 * MicroK8s is Kubernetes in a snap. Made by devs for devs.
   One quick install on a workstation, VM, or appliance.

   - https://bit.ly/microk8s
```

Hmm I want to get up to speed on this.  Try the quick install 

```
sudo snap install microk8s --classic
```

...done.  Wow that was easy!

...come back a few days later... ssh http not working.  VNC shows out of memory.  Reboot, find 300 crontab entries to start a monero miner.  

Turns out I have been contributing to cryptocurrency infrastructure!  Cool!  I've always thought about mining crypto!

Thanks, guys!

I had a firewall in place with only ssh+http+https access allowed, but it looks like I'm on a hostile internal subnet at my VM provider!  Whoops...good to know!

Somebody is getting crypto rewards for this at a monero wallet!  Cool!  Is it you guys?  If I change my downvote on Stephan's comments to upvotes will you send me a slice of the profits?  ;)

**Comment by Cryptophobia** [comment]
@jaredthirsk, did you delete your comment or did someone else delete it? I enjoyed reading that. And if you guys joined the scam and now you are hiding it, I want my share of monero as well. :moneybag: 

I opened a wallet and it's ready to go.

**Comment by sixcorners** [comment]
Binding to localhost is better but you are still vulnerable to dns rebinding attacks. Can this be a unix socket file like how docker does it? If not can it be secured using actual credentials?

**Comment by elwaxoro** [comment]
Note for people following behind that want the old behavior back:
edit `/var/snap/microk8s/current/args/kube-apiserver`, set `--insecure-bind-address=0.0.0.0`, then restart with `microk8s.stop` and `microk8s.start`

**Comment by ktsakalozos** [comment]
Closing this since insecure port was bound to 127.0.0.1 for a long time and is now completely removed.

**Comment by sixcorners** [comment]
Isn't there something more that can be done to prevent against dns rebinding attacks?
