### ISSUE TITLE
Support pre-installed local images

### ISSUE THREAD

**Issue by tonyespy** [ubuntu/microk8s#1136]
This issue is a request to support pre-installed local container images if/when microk8s is deployed as a confined snap. This comes from a real customer use case where a customer using the docker snap on Ubuntu Core wants to deploy their an applicance-like device (a RPi) with one or more of their container images pre-cached. Their container images are quite large, thus pre-seeding images would save on network-bandwidth and latency.

The only way they've been able to do this to-date is by creating a snap which provides a local docker registry. It would be nice if instead microk8s supported a standard content interface which would allow images delivered in another snap on the system to be consumed by microk8s.

**Comment by ktsakalozos** [comment]
Hi @tonyespy, thank you for opening this issue.

We could explore the "content" interface [1] in order to pre-populate the containerd cache.

Could you describe in more detail the local docker registry approach followed now? Would the registry addon `microk8s.enable registry` be of any use? Would it make sense to configure containerd to pull images from the docker registry the customer already deploys? I suspect there is already a workflow in place for managing this registry.

[1] https://forum.snapcraft.io/t/the-content-interface/1074

**Comment by ktsakalozos** [comment]
> Maybe... I'm not too familiar with the registry addon, so I'll have to give it a look before I can answer your question.

Here are a few doc pages you may find interesting:
- [Working with the built in registry](https://microk8s.io/docs/registry-built-in)
- [Adding a private registry](https://microk8s.io/docs/registry-private)
