### ISSUE TITLE
Microk8s add-node issue with multiple slave nodes.

### ISSUE THREAD

**Issue by deepakrbharadwaj** [ubuntu/microk8s#1240]
Hi Microk8s Team,

We are trying to setup a multinode cluster with microk8s.
To add slave nodes to the microk8s cluster, we are running the add-node command and generating the join command.

The token within that join command seems to be a single-use and with a TTL; and we need to run the add-node command everytime a new node needs to be added to cluster.

Is it possible to generate a multi use, non-expiring token just like in kubeadm. (Ref: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-token/).

This would help me in automating addition of slave nodes in my AWS environment.

**Comment by ktsakalozos** [comment]
Hi @deepakrbharadwaj 

We recently added the option to request tokens with a TTL as well as the option to set your own token instead of having one generated for you. This work is available in the `latest/stable` channel:
```
sudo snap install microk8s --classic --channel=latest/stable
```

The work on the token types is in [1]. Note that the `latest` track is better suited for ephemeral clusters as it will get upgraded to v1.19, v1.20, etc when released from upstream.

[1] https://github.com/ubuntu/microk8s/blob/master/scripts/cluster/add_token.py

**Comment by deepakrbharadwaj** [comment]
Thanks @ktsakalozos . I will test it out and update my findings
