### ISSUE TITLE
Kubeflow enable failure

### ISSUE THREAD

**Issue by alxchalkias** [ubuntu/microk8s#1443]
Hi team, microk8s enable kubeflow on my Dell Latitude (4cores 2.4G, 16GB RAM) workstation gave out the following issue. I'm using the HA branch.

[inspection-report-20200728_174555.tar.gz](https://github.com/ubuntu/microk8s/files/4989808/inspection-report-20200728_174555.tar.gz)
[kubeflow_addon_err.log](https://github.com/ubuntu/microk8s/files/4989809/kubeflow_addon_err.log)

**Comment by ktsakalozos** [comment]
The error here is not related to kubeflow. We fail to enable kubeflow here because we cannot configure the nodes of the cluster. There seem to be a few nodes registered that are unreachable (eg 10.93.108.118).

The main issue I see here is that we throw out the exception instead of displaying a meaningful error message.

**Comment by ktsakalozos** [comment]
Closed via https://github.com/ubuntu/microk8s/pull/1450
