### ISSUE TITLE
[HA] initial node in NotReady state fails when joining.

### ISSUE THREAD

**Issue by balchua** [ubuntu/microk8s#1448]
When the initial node is in `NotReady` state, joining another node will fail.
Propose to have `microk8s status --wait-ready` to wait until all nodes in the cluster are `Ready`.

**Comment by ktsakalozos** [comment]
There is a bug at https://github.com/ubuntu/microk8s/blob/master/scripts/wrappers/common/utils.py#L45 . We should be checking for " Ready" (note the space) because "Ready" is also part of "NotReady". This should make `microk8s status --wait-ready` to report True if any one of the nodes are Ready. Why do we need *all* nodes to be Ready?

**Comment by balchua** [comment]
Not really necessary to have all nodes to be in `Ready`. We just need the seed (or initial) node be in `Ready` state so joining nodes can join appropriately.
Yeah i saw this bug as soon as i created the issue. 😊

**Comment by balchua** [comment]
Fix merged. Closing the issue.
