### ISSUE TITLE
refresh failed

### ISSUE THREAD

**Issue by shojiro000** [ubuntu/microk8s#1469]
Now I'm using microk8s v1.18.4 on Ubuntu 18.04.1 and snap is tries to refresh it to v1.18.6, but it always fails at the same step.
I attach the log file.
[refresh-failed.log](https://github.com/ubuntu/microk8s/files/5019830/refresh-failed.log)

The error message in the log file is in Japanese.
> ln: シンボリックリンク '/var/snap/microk8s/1551/opt/cni/bin/bridge' の作成に失敗しました: ファイルが存在します

It means 
> ln: Failed to create symbolic link '/var/snap/microk8s/1551/opt/cni/bin/bridge'.: File exists.

Are there any workarounds?

**Comment by ktsakalozos** [comment]
Hi @shojiro000 what channel are you currently on? Can you share the output of `snap list microk8s` or the tarball produced by `microk8s.inspect`? Could you also share the output of `snap changes microk8s`? I need to understand what is the refresh path that is failing. Thank you.

**Comment by shojiro000** [comment]
Hi @ktsakalozos . Thank you for your response.
Here are some snap commands and outputs.
> root@oven:~# snap list microk8s
> Name      Version  Rev   Tracking       Publisher   Notes
> microk8s  v1.18.4  1503  latest/stable  canonical✓  classic
> root@oven:~# snap changes microk8s
> ID   Status  Spawn                   Ready                   Summary
> 175  Error   yesterday at 22:33 JST  yesterday at 22:41 JST  Auto-refresh snap "microk8s"
> 176  Error   today at 02:08 JST      today at 02:23 JST      Auto-refresh snap "microk8s"
> 177  Error   today at 10:48 JST      today at 10:54 JST      Auto-refresh snap "microk8s"
> 
> root@oven:~#
I don't think that you need to see the output of microk8s.inspect but if you do I'll share it.
Thank you.

**Comment by ktsakalozos** [comment]
What can you tell me about the deployment you have? How old is it? Where you always following the latest/stable channel? What addons do you have enabled? Any special configuration you have?

The `opt/cni/bin` is where kubernetes finds the CNI utils. The path to the cni utils used to be `/snap/microk8s/current/opt/cni/bin/`. With the multus support we moved the path to the cni utils in the writeable location `/var/snap/microk8s/current/opt/cni/bin/`. In doing so we create symlinks from the old location to the new one. The error message you see is that the creation of the symlink is failing because a file with the same name already exists. In [1] we 
create the new CNI location and properly symlink the utils. The CNI utils path is referenced in containerd configuration `/var/snap/microk8s/current/args/containerd-template.toml` and kubelet `/var/snap/microk8s/current/args/kubelet`.

An obvious fix for the issue you report is to check that k8s is not using the `/var/snap/microk8s/current/opt/cni/bin/`, remove it (take a backup just in case) and try to refresh the snap.

I would like however to understand how the deployment could have reached this state. Could it be a half finished refresh? What do you see with:
```
sudo ls -l /var/snap/microk8s/current/opt/cni/bin/
```

What are the contents of `/var/snap/microk8s/current/args/containerd-template.toml` and `/var/snap/microk8s/current/args/kubelet`?

[1] https://github.com/ubuntu/microk8s/blob/master/snap/hooks/configure#L299

**Comment by shojiro000** [comment]
Hi @ktsakalozos . Thank you for your information.
I'm using microk8s since April. Always using latest/stable channel.

Here attachments are the file list of directories and some files you requested.
[containerd-template.toml.txt](https://github.com/ubuntu/microk8s/files/5062115/containerd-template.toml.txt)
[kubelet.txt](https://github.com/ubuntu/microk8s/files/5062116/kubelet.txt)
[ls-snap-microk8s-current-opt-cni-bin.txt](https://github.com/ubuntu/microk8s/files/5062117/ls-snap-microk8s-current-opt-cni-bin.txt)
[ls-var-snap-microk8s-current-opt-cni-bin.txt](https://github.com/ubuntu/microk8s/files/5062118/ls-var-snap-microk8s-current-opt-cni-bin.txt)
[microk8s.status.log](https://github.com/ubuntu/microk8s/files/5062119/microk8s.status.log)

I'll try to refresh it after remove `/var/snap/microk8s/current/opt/cni/bin/`.
Thank you.

**Comment by shojiro000** [comment]
Hi. @ktsakalozos . 
Your workaround has worked.
If you need more information, I'll share them.
Thank you.

**Comment by apnar** [comment]
If I recall correctly before the merge of multus (and switch to default CNI bin to var with links), if calico was enabled it just copied all the CNI bin files over to /var/snap/microk8s/current/opt/cni/bin/ and never really cleaned them up.  Shouldn't be possible now, but for anyone who had enabled calico in the past (which I think came via HA?) they might need to manually clean them up before upgrading.

**Comment by ktsakalozos** [comment]
You are right @apnar. However, I do not think we ever exposed calico in latest/stable.

@shojiro000 is it possible you temporarily refreshed to latest/edge/ha-preview or tried to enable HA in any other way?
