### ISSUE TITLE
Upgrade Metallb

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1505]
I see https://github.com/ubuntu/microk8s/pull/1434 has been merged. I've just done a clean install on a single server with the latest/stable channel and noticed it still has version 0.8.2

This will have some small production workloads on it in the next few days and what worries me a bit is how I'm going to upgrade this seeing as I have a custom install of istio using istioctl using this and then quite a few istio gateways and virtual services.

Is there a better way to upgrade this than:
- `uninstalling istio and all gateways/virtual services`
- `microk8s disable metallb`
- `microk8s enable metallb`
- `reinstallaing istio and all gateways/virtual services`

I will have this same problem when future metallb versions come out so would rather try and understand the best to do it now.

**Comment by sstubbs** [comment]
It's only really metallb I'm worried about as I'm using istioctl for istio which allows upgrades. Certmanager also depends on both istio and metallb so I would like to try and get a clean way of updating it.

**Comment by ktsakalozos** [comment]
The metallb update is merged in master and you should be able to find it in latest/beta.

If you are doing a production deployment it is better you install MicroK8s from specific channel eg `sudo snap install microk8s --classic --channel=1.18/stable` and avoid the latest track (latest/stable, latest/beta etc). If you for example follow the 1.18/stable channel you will be getting k8s patch releases (1.18.8, 1.18.9 etc) and any other security fixes we need to push. The latest channel is subject to backwards breaking changes such as deprecation of APIs when a minor releases comes out eg from 1.18 to 1.19, addon upgrades eg the metallb you mention. Due to this kind of breaking changes the method of snap refresh to a channel you desire may not work. A snap refresh will try to run the version of services in the selected channel with the current configuration and it may fail.
