### ISSUE TITLE
Pod to service connectivity lost after upgrade to microk8s snap version 1.18.8

### ISSUE THREAD

**Issue by mkretz** [ubuntu/microk8s#1524]
[inspection-report-20200828_084931.tar.gz](https://github.com/ubuntu/microk8s/files/5141632/inspection-report-20200828_084931.tar.gz)

We have upgraded our microk8s one node instance running on Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-112-generic x86_64) from snap version 1.18.6 to snap version 1.18.8. After the upgrade everything was first looking fine. Then after a reboot of the node, all of our pods lost connectivity to all services (type ClusterIP) which they are talking to. We noticed that pod to pod connectivity ist still working. Only pod to service connectivity is affected. Here's an example of a pod and a service:

```
this@citbuild:~$ kubectl get pod mds-mongodb-deploy-6d769cbbc9-xjrmf -o wide
NAME                                  READY   STATUS    RESTARTS   AGE     IP          NODE         NOMINATED NODE   READINESS GATES
mds-mongodb-deploy-6d769cbbc9-xjrmf   1/1     Running   18         2d19h   10.1.1.39   citads-dev   <none>           <none>
this@citbuild:~$ kubectl get svc mongodb
NAME      TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
mongodb   NodePort   10.152.183.26   <none>        27017:31712/TCP   65d
```

Then, from an other pod we see

```
/ # nc -v 10.1.1.39 27017
10.1.1.39 (10.1.1.39:27017) open
```
but
```
/ # nc -v 10.152.183.26 27017
nc: 10.152.183.26 (10.152.183.26:27017): Connection timed out
```
We have checked the kube-proxy logs and iptables on the node `citads-dev` according to the [k8s networking troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#is-the-kube-proxy-working) and both look ok (glad to look more closely, if anyone has specific things to check).

Does anyone have any hints on how to analyze this further? Feel free to let us know, of you need more information.

**Comment by ktsakalozos** [comment]
@mkretz I see that there are services reported with `kubectl get svc` but the `ServiceList` in `kubectl cluster-info --dump` is almost empty.  Is there anything special with the deployment you have? Anything that may interfere with the network/firewall of the node? How did you do the upgrade? Just checked that it has been months since we pushed anything to the 1.18 branch [1] so the only thing that changed should be the k8s binaries but I do not see anything in the change log [2].

[1] https://github.com/ubuntu/microk8s/commits/1.18
[2] https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#downloads-for-v1188

**Comment by mkretz** [comment]
@ktsakalozos the point about the service list not matching is indeed strange. We will investigate that. Thanks for the hint!

There is nothing special about the deployment, at least not intentionally. It's a snap-based microk8s on an Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-112-generic x86_64) server.
