### ISSUE TITLE
Causing issues for wireguard VPN (iptables)

### ISSUE THREAD

**Issue by VictorNine** [ubuntu/microk8s#1541]
I'm running microk8s channel=1.19 on ubuntu 18.04. I have a wireguard connection to my master node witch works perfectly as long as microk8s is not running. As soon as it's started the wireguard connection stops working. This issue seems to be in iptables:

`DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000`

Any idea how to resolve this problem?
Removing the FwMark from the wireguard config works but still a strange issue

Similar problem with more info https://github.com/ubuntu/microk8s/issues/688

**Comment by balchua** [comment]
I don't think this is a. MicroK8s issue.  But someone seems to have a solution to this.

https://discuss.kubernetes.io/t/kubernetes-wireguard-flannel-overlay-network-on-vms-blocked-by-kubefirewall/4602

Can you try this one?

**Comment by daniel-widrick** [comment]
> `DROP all -- anywhere anywhere /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000`

Why does microk8s need this rule in place? Dropping marked packets seems like the nuclear approach...

**Comment by neoaggelos** [comment]
Just adding a quick note that any of these rules are not specific to MicroK8s, but rather come from the upstream Kubernetes components. MicroK8s cannot, should not and will not remove this rule, since it could break Kubernetes in unexpected ways.

If running MicroK8s on a host with wireguard VPN, you need to make sure that there are no conflicts between the iptables rules that Kubernetes and wireguard VPN need.
