### ISSUE TITLE
Update to 1.19 possible kube-proxy IPv6 issue

### ISSUE THREAD

**Issue by dhcode** [ubuntu/microk8s#1549]
Today I got an update to 1.19.
After that some pods were not starting, because they could not resolve dns names of other services.

Inspect showed that snap.microk8s.daemon-proxy is down.
The logs state:

> I0908 22:02:00.899360   11341 node.go:136] Successfully retrieved node IP: 2a01:*****
> I0908 22:02:00.899390   11341 server_others.go:108] kube-proxy node IP is an IPv6 address (2a01:*****), assume IPv6 operation
> W0908 22:02:00.908142   11341 server_others.go:579] Unknown proxy mode "", assuming iptables proxy
> I0908 22:02:00.908187   11341 server_others.go:186] Using iptables Proxier.
> F0908 22:02:00.908199   11341 server.go:495] unable to create proxier: CIDR 10.1.0.0/16 has incorrect IP version: expect isIPv6=true
> snap.microk8s.daemon-proxy.service: Main process exited, code=exited, status=1/FAILURE

It seems like now it is using the IPv6 address of the host.

I tried to add the options `--bind-address=0.0.0.0 --feature-gates=IPv6DualStack=false` to /var/snap/microk8s/current/args/kube-proxy but it did not help.

I still don't know how to fix it.

*report removed*

**Comment by dhcode** [comment]
Thanks to @kjackal in the #microk8s Slack and some research we found out, that the behavior of detecting the protocol in kube-proxy has changed. See: https://github.com/kubernetes/kubernetes/commit/56df70b639c5b5bf53076a3483a2e40b8f60c49a#diff-934760ea1a4e195e49bcd10625cf4e46

The --bind-address= needs to be set to a specific IP address, not 0.0.0.0 to force the IPv4 mode. Then it works again.

**Comment by ktsakalozos** [comment]
Thank you for reporting this @dhcode and for finding a solution.

If I may add, since you have a long lasting, non-ephemeral deployment you could consider following a specific channel. This way you do not have to deal with such annoyances every time the `latest/stable` changes to a new minor release. For instance if you `sudo snap install microk8s --classic --channel=1.19` you will be getting updates of the 1.19 release and you will not automatically be switched to 1.20 when it comes out. See [1].

[1] https://microk8s.io/docs/setting-snap-channel
