### ISSUE TITLE
daemon-control-plane-kicker is trying to check a non-existent folder /var/snap/microk8s/1668/var/kubernetes/backend (script related to dqlite migration ??)

### ISSUE THREAD

**Issue by zzOzz** [ubuntu/microk8s#1572]
Please run `microk8s inspect` and attach the generated tarball to this issue.

[inspection-report-20200916_103002.tar.gz](https://github.com/ubuntu/microk8s/files/5230866/inspection-report-20200916_103002.tar.gz)

-> log file
microk8s.daemon-control-plane-kicker[38558]: chmod: cannot access '/var/snap/microk8s/1668/var/kubernetes/backend': No such file or directory

**Comment by ktsakalozos** [comment]
Hi @zzOzz,

Yes you are right, this output is because the node got updated to 1.19 but has not yet migrated to dqlite. I am sure it is not causing any issues apart from the message annoyance. I did put a PR up to fix this.

Also I see you have a long lasting deployment. In such cases it is recommended to follow a specific release channel [1] so you do not get affected by breaking changes introduced by either upstream or MicroK8s.

[1] https://microk8s.io/docs/setting-snap-channel
