### ISSUE TITLE
Enabling Cilium With ha-cluster

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1619]
Hi,

With a single node I've had issues with networking not working between pods after I run `microk8s stop` and `microk8s start` 

It seems to happen with both ha-cluster enabled and disabled. With ha-cluster disabled if I enable cilium this seems to fix it. Cilium also seems to retain source ip addresses of requests as flannel does.

I'm wondering can I enable cilium with ha-cluster enabled? I'm not sure how deeply calico is needed by the ha-cluster plugin. I intend to use 2 more servers to setup a 3 node cluster but this networking issue would be quite a big problem in a production cluster so I'm hoping cilium would be the way to fix it until I can get better stability out of flannel or calico.

**Comment by sstubbs** [comment]
I didn't mention I'm using 1.19/stable

**Comment by balchua** [comment]
Hello @sstubbs 

> With a single node I've had issues with networking not working between pods after I run microk8s stop and microk8s start

Does this mean pods can't talk to each other intermittently?  I recall for calico, this can be an issue for nodes with multiple interfaces.  Could it be the case? Like the one here? https://github.com/ubuntu/microk8s/issues/1554#issuecomment-691426908

As far as i know the use of calico is nothing especially related to HA, other than it uses the apiserver instead of directly etcd.  Since from 1.19 MicroK8s dqlite is the default.

I haven't got the chance to use cilium on a multi node ha cluster for a significant time.

Also, i will probably wait for some fixes on the 1.19 MicroK8s to arrive before putting this up for prod.  But if you're up for a test, that will be great too. 😊

Thanks once again!

**Comment by sstubbs** [comment]
Hi @balchue

It seems itermittent. Only a few pods seem to have this issue and it seems random as each time it's different pods in different namespaces giving me this each time I restart.

I would rather stick with 1.19 to be honest as I need quite a bit of time getting everything up and running each time and if more work is going into the new ha solution that is definitely preferable for me. I have backups so it's not the end of the world if there are problems.

So if I enable cilium will this revert to flannel and install cilium in addition to flannel? Just trying to understand what I'm actually doing. If i disable cilium will it go back to calico?

**Comment by balchua** [comment]
If the cluster is an ha-cluster, it will fall back to calico when Cilium is disabled.  But if you disable ha, the it ideally should fall back to flannel (but i've not tried this)

**Comment by sstubbs** [comment]
ok thanks for the clarification.

**Comment by sstubbs** [comment]
This issue can probably be closed then.

**Comment by balchua** [comment]
Thanks
