### ISSUE TITLE
feature request: microk8s.[start|stop]

### ISSUE THREAD

**Issue by kwmonroe** [ubuntu/microk8s#162]
The current mix of `enable|disable` is confusing. We have these that affect _addons_:
```
microk8s.disable foo
microk8s.enable foo
```

And these that affect the microk8s _service(s)_:
```
sudo snap disable microk8s
sudo snap enable microk8s
```

This leads to a UX like this:
```bash
## /me wants to save my battery, so i turn off microk8s
ubuntu@bionic:~$ sudo snap disable microk8s
microk8s disabled

## time has passed and I want to interact with k8s again
ubuntu@bionic:~$ microk8s.enable

Command 'microk8s.enable' not found, but can be installed with:

sudo snap install microk8s

## /me grumbles because i confused snap vs microk8s enable

## worse, /me forgets that i disabled microk8s and do what the output says
ubuntu@bionic:~$ sudo snap install microk8s --classic
snap "microk8s" is already installed, see 'snap help refresh'
```

I would like to have control over the running services within microk8s without resorting to snap actions. I propose `microk8s.[start|stop]`, which would do the right thing to relevant system services.

If `microk8s.stop` has been run, future calls to `microk8s.*` should notify the user appropriately, as in:
```bash
ubuntu@bionic:~$ microk8s.stop
microk8s stopped

ubuntu@bionic:~$ microk8s.enable dashboard
microk8s is not running, try microk8s.start
```

**Comment by ktsakalozos** [comment]
Thank you for opening the issue @kwmonroe. To add to the confusion there is also the `snap start/stop microk8s` option.

I am a big +1 for making microk8s aware of its state also for another reason. During installation and a disable/enable cycle `microk8s.kubectl` is not be able to reach the apiserver and throws out potentially confusing messages. Since we will work into improving the UX with the stop/start commands we should also make sure we should let know the user when microk8s is starting and of course return meaningful return codes (https://github.com/ubuntu/microk8s/issues/115). Look how ugly the sleep command is in the installation instructions of microk8s https://github.com/geoand/sb-fmp-microk8s .
