### ISSUE TITLE
Kubeflow issue  export GITHUB_TOKEN=${YOUR_GITHUB_TOKEN} and spartakus.jsonnet  

### ISSUE THREAD

**Issue by ttosss** [ubuntu/microk8s#163]
we have two issues  f
a) or stable installation on ubuntu 16 gives 
#The GITHUB_TOKEN environment variable isn't set  
https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

The kybernets installation goes smoothly however 
the kubeflow Install Kubeflow Set environment variables is a mess you have to ensure it will be in .bashrc

export KUBECONFIG=/snap/microk8s/current/client.config
export GITHUB_TOKEN=${YOUR_GITHUB_TOKEN}
at least for ECS replace your_github_token with your GitHub token
export GITHUB_TOKEN=your_github_token
and add to .bashrc
Once that is set correctly, we will persist it for future terminals:
checck
  echo "export GITHUB_TOKEN=${GITHUB_TOKEN}" >> ~/.bashrc

spartakus.jsonnet  seems not to be able to inactivate

**Comment by ktsakalozos** [comment]
Hi @ttosss ,

Thank you for reporting this. If I remember correctly, there is no need to have GITHUB_TOKEN defined anymore. There used to be a I/O rate limitation from github that is lifted now. @carmine may be able to provide more insight on this.

Regarding `spartakus.jsonnet` could you help me reproduce the issue you are having? Please go into as much detail as possible since I am not a regular kubeflow user.

Thank you for using microk8s.

**Comment by carmine** [comment]
The latest versions of kubeflow kfctl.sh / install scripts do download a tarball of kubeflow, which then allows kubeflow to point to the local download. This might be the appropriate/best way to go. However, you do lose the ability to specify a particular version of a ksonnet package (ie using the versioning information in github).

This doesn't appear to be a microk8s issue per se, or is there something about microk8s that is failing here?
