### ISSUE TITLE
microk8s.daemon-apiserver fails to start with unknown flag --storage-dir

### ISSUE THREAD

**Issue by ralfstx** [ubuntu/microk8s#1790]
Fresh install on Ubuntu 18.04.5 LTS with `sudo snap install microk8s --classic --channel=1.20/edge`.
From `sudo journalctl -u snap.microk8s.daemon-apiserver -r`:

```
...
Dec 03 09:28:54 snaut systemd[1]: snap.microk8s.daemon-apiserver.service: Failed with result 'exit-code'.
Dec 03 09:28:54 snaut systemd[1]: snap.microk8s.daemon-apiserver.service: Main process exited, code=exited, status=1/FAILURE
Dec 03 09:28:54 snaut microk8s.daemon-apiserver[8304]: Error: unknown flag: --storage-dir
Dec 03 09:28:54 snaut microk8s.daemon-apiserver[8304]: + exec /snap/microk8s/1788/kube-apiserver --cert-dir=/var/snap/microk8s/1788/certs --service-cluster-ip-range=10.152.183.0/24 --authorization-
Dec 03 09:28:54 snaut microk8s.daemon-apiserver[8304]: + '[' -f /snap/microk8s/1788/kube-apiserver ']'
Dec 03 09:28:54 snaut microk8s.daemon-apiserver[8304]: #~Enable the aggregation layer)'
...
Dec 03 09:28:54 snaut microk8s.daemon-apiserver[8304]: --storage-dir=${SNAP_DATA}/var/kubernetes/backend/
...
```

[inspection-report-20201203_093334.tar.gz](https://github.com/ubuntu/microk8s/files/5634782/inspection-report-20201203_093334.tar.gz)

**Comment by recklessop** [comment]
I am seeing the same thing on Ubuntu 20.10 with 1.20/edge as well. 

Just as a side note, I had 1.19 installed with the storage plugin. Then refreshed to 1.20/edge.

I tried uninstalling and purging microk8s, but this issue comes back after the reinstall 

It looks like the storage line is coming from the default args directory, https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/kube-apiserver

So probably something that will also happen on a default install.

**Comment by brotherdust** [comment]
I too, am suffering from this on both 1.19/stable and 1.20/beta. Has anyone found a fix for this?
Thanks!

**Comment by balchua** [comment]
Seems to be good now.  Just tried `1.20/edge`.  There's also an update a few days ago.

```
  1.20/stable:      v1.20.0  2020-12-11 (1864) 219MB classic
  1.20/candidate:   v1.20.0  2020-12-11 (1864) 219MB classic
  1.20/beta:        v1.20.0  2020-12-11 (1864) 219MB classic
  1.20/edge:        v1.20.0  2020-12-15 (1875) 219MB classic
```
