### ISSUE TITLE
microk8s status --wait-ready just hangs

### ISSUE THREAD

**Issue by johngrabner** [ubuntu/microk8s#1854]
`microk8s inspect` attached.

```
sudo snap install microk8s --classic --channel=latest/stable
microk8s status --wait-ready
```
above will hang.

Just upgraded PC to ubuntu 20.04 and wanted a clean install of microk8s.
so did a snap remove microk8s, then tried to reinstall. 1.20 it failed, so I removed and tried 1.19.

Lots of errors  

`Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized`

`grpc: addrConn.createTransport failed to connect to {/var/snap/microk8s/common/run/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/common/run/containerd.sock: connect: no such file or directory". Reconnecting...
`

[inspection-report-20201229_144038.tar.gz](https://github.com/ubuntu/microk8s/files/5752108/inspection-report-20201229_144038.tar.gz)

[inspection-report-20201229_140058.tar.gz](https://github.com/ubuntu/microk8s/files/5752085/inspection-report-20201229_140058.tar.gz)

Just a PC running ubuntu 20.04, no VM involved.

**Comment by johngrabner** [comment]
A reboot after removing microk8s and before installing microk8s fixed the issue.

**Comment by balchua** [comment]
Hi @johngrabner 
Thanks for reporting this.  I think it is because the `calico-node` isn't running. It is missing several resources auch as the `ServiceAccount` used by calico.

If you dont mind, can you apply the cni manifest which is located at `/var/snap/microk8s/current/args/cni-network/cni.yaml`?

Once you do that, you should have the calico-node pod, the calico service accounts showing up in the kube-system namespace.

I don't know what exactly happened during the upgrade. Sorry bout that.

**Comment by johngrabner** [comment]
I'm sorry, I reformated the HD, reinstalled ubuntu and microk8s. So this environment is lots.
