### ISSUE TITLE
microk8s windows install on home edition

### ISSUE THREAD

**Issue by neelabhm** [ubuntu/microk8s#1965]
I just tried the windows installer on my machine licensed home edition. The install had the hyper-v option greyed out.. Only virtual box was enabled. While it is true that generally client side hyper-v is available on the pro sku, a home user can still enable hyper-v role on windows home. Shouldn't we be checking for function availability instead of an os version check  ?
![image](https://user-images.githubusercontent.com/75085684/106706040-08a04680-6615-11eb-845c-af290c2555db.png)

**Comment by neelabhm** [comment]
and as I had expected, a simple reg value change from "Home" to "Pro" as shown below tricks the multipass installer to detect Hyper-V on my actually home edition. 
![image](https://user-images.githubusercontent.com/75085684/106741082-4024e800-6641-11eb-8cae-2f09dcd348d2.png)

**Comment by neelabhm** [comment]
and with that here's the bat script which one could use to enable hyper-v on a home machine

```
pushd "%~dp0"

dir /b %SystemRoot%\servicing\Packages\*Hyper-V*.mum >hyper-v.txt

for /f %%i in ('findstr /i . hyper-v.txt 2^>nul') do dism /online /norestart /add-package:"%SystemRoot%\servicing\Packages\%%i"

del hyper-v.txt

Dism /online /enable-feature /featurename:Microsoft-Hyper-V-All /LimitAccess /ALL
```

**Comment by joedborg** [comment]
Hi @neelabhm, thanks for the report.  The reason we do this is because hyper-v isn't officially supported on Home (https://docs.microsoft.com/en-us/archive/blogs/canitpro/step-by-step-enabling-hyper-v-for-use-on-windows-10).  We need to discuss, internally, whether or not we want to support this.  In the mean time, you can install with the VirtualBox target and then run:

```
multipass set local.driver=hyperv
```

After which, you can run:

```
microk8s install ...
```

**Comment by neelabhm** [comment]
sure @joedborg I understand that, thank you.
