### ISSUE TITLE
microk8s group permissions require reboot, not "next login"

### ISSUE THREAD

**Issue by galgalesh** [ubuntu/microk8s#2011]
When the user has insufficient permissions to access microk8s, they get asked to run two commands and told "The new group will be available on **the user's next login**."

https://github.com/ubuntu/microk8s/blob/cb487d8e4363c15462eb0c7dc28f780c0dd2a6a5/microk8s-resources/actions/common/utils.sh#L6-L12

This implies that logging out and in again will solve the issue after running those commands. This is not the case, however. A reboot is required. I just tested this on my standard Ubuntu 20.04 Desktop after installing microk8s for the first time.

[inspection-report-20210215_164323.tar.gz](https://github.com/ubuntu/microk8s/files/5982598/inspection-report-20210215_164323.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @galgalesh nice to see you around. I am sure you see that the purpose of the re-login is to get the user groups re-loaded. You are right a new login may not be enough, see [1]. We should not be relying to such a flake process. Instead we should suggest a safe path, eg: "Note that the user groups need to be reloaded either via a reboot or the use of su or newgrp."

@galgalesh, since I see you have already looked at the code, would you be interested in a PR to fix this? The files that we need to patch are [2] and [3].

[1] https://askubuntu.com/a/1046365
[2] https://github.com/ubuntu/microk8s/blob/cb487d8e4363c15462eb0c7dc28f780c0dd2a6a5/microk8s-resources/actions/common/utils.sh#L6-L12
[3] https://github.com/ubuntu/microk8s/blob/cb487d8e4363c15462eb0c7dc28f780c0dd2a6a5/scripts/wrappers/common/utils.py#L151

**Comment by galgalesh** [comment]
Hi @ktsakalozos , nice to see you too :wave: 

I submitted a PR for this: https://github.com/ubuntu/microk8s/pull/2021
