### ISSUE TITLE
 Portainer addon can't find Storage Class Addon.

### ISSUE THREAD

**Issue by seffyroff** [ubuntu/microk8s#2076]
Please run `microk8s inspect` and attach the generated tarball to this issue.
[inspection-report-20210305_202932.tar.gz](https://github.com/ubuntu/microk8s/files/6093263/inspection-report-20210305_202932.tar.gz)
We appreciate your feedback. Thank you for using microk8s.
1: On a fresh cluster I have enabled several plugins including Portainer and Storage.
2: I've port-forwarded the portainer service to access the web interface locally
3: After creating an admin user, the configuration page complains there is no storage class detected.
Screenshot:
![ksnip_20210305-123245](https://user-images.githubusercontent.com/8338529/110170529-3d5d1480-7df2-11eb-995f-300ccd89135c.png)
I suspect the issue is more serious than this, and more likely a general connectivity issue that I need to provide configuration for.  Installing Portainer by following their own guide results in a functional service however.

**Comment by balchua** [comment]
I think this is because the portainer addon is using the `storage` addon which is really just a hostpath.
Since you are running a multi node cluster, there is a chance that portainer couldn't find the persistentvolume.
I can see that your have `rook/ceph`, if you can set rook as the default the `StorageClass` and make the `microk8s-hostpath` `StorageClass` as none default it might work.

You may need to disable and enable portainer addon.

We still do not have a good story on persistent volume with a multi node MicroK8s.

**Comment by seffyroff** [comment]
Thanks for the helpful reply! It's good to know that pv on multinode is not yet ticking all the boxes.  I'll persevere with bringing Ceph up fully to provide pvs.
