### ISSUE TITLE
Failing to re-add the node after it has been rebuilt

### ISSUE THREAD

**Issue by hugeps** [ubuntu/microk8s#2212]
Given 3 node cluster v1.21 on Pi4-B-8gb with Ubuntu 20.04.2 LTS 64bit.

original config has 3 nodes running.
pi3 dies

following command performed:
```
microk8s.kubectl delete node pi3
```

node removed successfully

now we've rebuilt the node3 with the same IP and trying to join cluster, but:

```
Contacting cluster at 192.168.178.71
Connection failed. The joining node (192.168.178.73) is already known to dqlite. (504).

pi2:~$ microk8s status
microk8s is running
high-availability: yes
  datastore master nodes: 192.168.178.71:19001 192.168.178.72:19001 192.168.178.73:19001

```

Indeed the .73 seems to be known to microk8s

Trying to remove from MicroK8s:

```
pi1:/var/snap/microk8s/current/var/kubernetes/backend$ microk8s remove-node 192.168.178.73
Error from server (NotFound): nodes "192.168.178.73" not found
Node 192.168.178.73 does not exist in Kubernetes.
```

Question:
- is it possible to purge the node from microk8s configuration given its not already in K8s

**Comment by balchua** [comment]
Hi @hugeps
Normally when you want to service a node, you first need to do `microk8s leave` on the departing node followed by a `microk8s remove node` done on any node that is still in the cluster so that you can add it back later on.

Since it is already "removed" from kubernetes cluster, you can follow the instruction here on how to forcefully remove the node in dqlite.

**Comment by hugeps** [comment]
Cheers for the advice!  Indeed  the force remove worked.
Node was actually crashed beyond repair, but the mistake made is - needed to use microk8s remove-node instead of the kubernetes one...
