### ISSUE TITLE
can't push local container registry

### ISSUE THREAD

**Issue by bownie** [ubuntu/microk8s#2246]
Hi,

I'm on a mac and trying to push to local registry as per instructions here:

https://microk8s.io/docs/registry-built-in

I'm getting:

$ docker push localhost:32000/wordpress-xyglo
Using default tag: latest
The push refers to repository [localhost:32000/wordpress-xyglo]
Get http://localhost:32000/v2/: dial tcp [::1]:32000: connect: connection refused

Have tried workarounds suggested with /etc/hosts (both for adding a non localhost/127.0.0.1 entry and for removing IPv6 loopback) in here:

https://github.com/ubuntu/microk8s/issues/196

Nothing is working.  Is there an up-to-date statement on how to troubleshoot this?  Many thanks

**Comment by bownie** [comment]
also another dumb question - I created a support tarball but can't access it:

Building the report tarball
  Report tarball is at /var/snap/microk8s/2128/inspection-report-20210506_104422.tar.gz

but it's not accessible on my local machine at that path

**Comment by ktsakalozos** [comment]
Hi @bownie, MicroK8s on Mac and windows runs in a VM. Assuming you have used the MicroK8s installers that VM is setup with mulipass [1] and is paired with a few native scripts so that for example `microk8s kubectl` is forwarded in the VM. So, the registry you setup is not on localhost but is available in the VM running MicrosK8s. Try `multipass list` to see the VMs and `microk8s info <vm_name>` to find its IP.

[1] https://multipass.run/docs

**Comment by bownie** [comment]
Perfect.  Thanks for the education - it's now working!
