### ISSUE TITLE
Suggestion: Microk8's Package Manager   

### ISSUE THREAD

**Issue by horvatic** [ubuntu/microk8s#2251]
## Overview

As a user it would be useful to have a Microk8's Package Manager for addons of any kind, 1st or 3rd party.

For 3rd party I should be able to point to a repo with a standard layout and deploy the addon to a namespace.
Example:
```
$ microk8s pm add https://github.com/horvatic/K8s-Status-Discord-Bot/tree/main/bot/deploy --secrets discord-bot:bot-token=123
```
NOTE: the layout of this repo isn't what I suggest for a standard, I am just using it as an example

Then I should be able to do a list of all my plugins 1st or 3rd party.
Example:
```
$ microk8s pm list
   horvatic/K8s-Status-Discord-Bot
```

I should also be able to remove any package when I am done
Example:
```
$ microk8s pm remove horvatic/K8s-Status-Discord-Bot
```

This is what a user might see if a ```microk8s pm help``` command is issued
```
$ microk8s pm help
  add - add a plugin, takes a git repo URI
        options:
            --configs - Override configs values in config maps
            --secrets - Override secrets values in config maps
            --namespace - Override deployment namespace
   remove - removes plugin, takes a current plugin name
   list - list all currently installed plugin
```

## Why I don't like the current system
It excludes 3rd party dev tools, along with not allowing me to override settings.
I also have no idea what / where stuff is deployed until I deploy it using the addon tool. 
More control is useful too. I should be able to fork a microk8's official addon git repo, and make my own flavor. 

## Why not just clone repos and use their deployments?
If I could have most of my plugins using a "package manager" over 3 or 4 using the official addon tool, and a few random repos that I need to keep track separately causing issues. Having one place to manage the current state of my cluster is very powerful! This will also enforce a standard setup for plugins, thus it will be easier to read / debug

**Comment by balchua** [comment]
@horvatic 
Thanks for putting this one.  there's also an issue similar to what you mentioned.
https://github.com/ubuntu/microk8s/issues/1680
I like the idea of de-coupling the addons from MicroK8s.  First, addons can be upgraded without cutting a MicroK8s release.
@ktsakalozos @joedborg any thoughts?

**Comment by horvatic** [comment]
Is this feature on a roadmap? If not I could fork the repo, and POC an independent package manager application. Maybe keep it under /packagemanager. Once done a PR would be created. Thoughts / Worth the time?

**Comment by ktsakalozos** [comment]
@horvatic the support of external repos is not on the roadmap, so a PoC would be helpful at this point. Before diving into the implementation could we spec a bit more the pm command and how it would work?

There are some ideas to support 3rd party repositories serving as collections of addons. Currently, addons are enabled and disabled with `microk8s enable <addon>` and `microk8s disable <addon>` respectively. The addons shipped with microk8s are scripts found in [1] and there is also a list of metadata about each one of them in [2]. The problem we are facing is that we cannot extend the list of addons indefinitely because:

  - addons involve some maintenance cost
  - addons are often not ready at the day of the release of k8s (eg at the time v1.21 was released some addons may be broken)

We were thinking of having a repository of "core" addons and 3rd party/community driven repositories with curated addons. For example, core addons would be DNS, ingress etc, but a K8s-Status-Discord-Bot would be part of a community effort.

Your suggestion of `microk8s pm add <git-repo>` would add a 3rd party repository that would include multiple addons. Of course not all addons will work with all k8s versions so the git repo should have branches corresponding to the the kubernetes release. For example in the `<git-repo>` you would have a 1.21 branch for addons compatible with k8s v1.21.

The `--config`, `--secret` and `--namespace` are specific to each addon so at this point lets not bother with them. It is on our roadmap to specify a "framework" for implementing addons. In this "framework" we should come up with good practices and common guidelines on how to configure addons so we provide a uniform UX.

Your thoughts?

Also adding @chris-sanders our, eng manager.

[1] https://github.com/ubuntu/microk8s/tree/master/microk8s-resources/actions
[2] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/addon-lists.yaml

**Comment by ktsakalozos** [comment]
How would your suggestion compare to helm?

**Comment by horvatic** [comment]
Helm is "The package manager for Kubernetes", which does allow custom configuration values, along with some other great features. If the repo follows a helm flow it will be very simple to implement. 

What I am suggesting is a "microk8's" layer that abstracts helm, kustomize, and raw yaml deployments. 

NOTE: If I use  ```microk8s pm add https://github.com/horvatic/helmrepo``` and I do not have helm installed on my cluster an error should be thrown. Something like "helm is not install on the cluster, please run the follow command to install helm"

The microk8's layer should also enable me to list my packages, remove packages, update to a new version of a package, all of those sort of things.

What are your thoughts?

**Comment by horvatic** [comment]
Closing as the issue is stale, and I haven't needed this feature
