### ISSUE TITLE
armhf support

### ISSUE THREAD

**Issue by qm3ster** [ubuntu/microk8s#228]
Is `armhf` support in the works?
`snap install microk8s --classic --beta` says that it is only published for `(amd64, arm64)` (as opposed to `(amd64)` without `--beta`).
It looks like this snap can be *built* on `armhf`, if you search that word in this repo.

**Comment by ktsakalozos** [comment]
Hi @qm3ster ,

We are not currently working on armhf, but we might do in the future.

Now that we have arm64 in our release process, supporting additional architectures is straight forward. I guess we are looking for some incentives to do so.

If you (or anyone else) are willing to lend a hand here what is entailed:
 - make sure the k8s core binaries are available in the architecture we target (https://github.com/ubuntu/microk8s/blob/master/build-scripts/fetch-binaries.sh).
 - review the addons so that the images pulled are appropriate (https://github.com/ubuntu/microk8s/blob/master/build-scripts/fetch-binaries.sh). If no images are available we can either host an image build or just remove the addon during snap build as we do for istio, gpu etc (https://github.com/ubuntu/microk8s/blob/master/snapcraft.yaml#L178)

On our end we will enable the new architecture on the launchpad builders (https://kyrofa.com/posts/building-your-snap-on-device-there-s-a-better-way) and you will get on the edge channel a new build upon every commit. For pushing to beta/stable channels we will need to connect our ci to the respective hardware pool but that is internal.

Cheers!
