### ISSUE TITLE
MicroK8s hosting Wireguard server restarts on client connect

### ISSUE THREAD

**Issue by danackerson** [ubuntu/microk8s#2328]
Deploying a wireguard server charm to MicroK8s via juju, I'm able to verify the server is up & running with the configured settings via `wg show wg0`.

However, on trying to connect to this server from my localhost, MicroK8s is immediately terminated. It comes up after a few minutes on its own.

Running $ juju --version -> 2.9.4-ubuntu-amd64
& MicroK8s snap v 1.20.7

**Comment by danackerson** [comment]
Now able to upload the report: [inspection-report-20210610_112858.tar.gz](https://github.com/ubuntu/microk8s/files/6630119/inspection-report-20210610_112858.tar.gz)

**Comment by ktsakalozos** [comment]
I believe MicroK8s restarts because it gets reconfigured for the new interfaces Wireguard creates.

If this is something you do not want you can add the `--bind-address=0.0.0.0` argument in the `/var/snap/microk8s/current/args/kube-apiserver` and restart MicroK8s. Would this address the issue you are having?

**Comment by danackerson** [comment]
> I believe MicroK8s restarts because it gets reconfigured for the new interfaces Wireguard creates.
> 
> If this is something you do not want you can add the `--bind-address=0.0.0.0` argument in the `/var/snap/microk8s/current/args/kube-apiserver` and restart MicroK8s. Would this address the issue you are having?

Indeed, this resolved my issue. Thanks @ktsakalozos !
