### ISSUE TITLE
Remove dependency on Snap

### ISSUE THREAD

**Issue by BryanDollery** [ubuntu/microk8s#2714]
Feature Request:

Please, please, please remove your dependency on snapd. I am a senior enterprise architect and I'd really like to use your software and recommend it to my clients, but I won't touch snapd with a barge-poll because "security", and also, "common sense". In a security-conscious corporate setting, I have no choice but to avoid snap. 

B

**Comment by ktsakalozos** [comment]
Hi @BryanDollery thank you for reaching out.

MicroK8s is a Kubernetes distribution based on snaps. If we were to ship a k8s distribution that is not a snap it wouldn't be called MicroK8s, it would have been a different project.

I am going to close this issue since we do not want to give the wrong impression that moving away from snaps is something that can be addressed in the context of this project.
