### ISSUE TITLE
Is there a way to use host docker daemon?

### ISSUE THREAD

**Issue by snowmansora** [ubuntu/microk8s#287]
Currently, microK8s use its own docker daemon, which is good for isolation.
However, is there any way to use the host docker daemon instead? (e.g. a configuration)

Reason is that I will build a new docker image on the host, and I would like to test it via a K8s pod inside microK8s. That is not working at the moment because the microK8s docker daemon doesn't has the image I built locally unless I transfer the image to it.

Thank you in advance!

**Comment by ktsakalozos** [comment]
Hi @snowmansora 

Here are a few options you have:

- Use the registry addon to push your image to so that it becomes available to MicroK8s. To start the registry you `microk8s.enable registry`. Then you will need to tell the host's dockerd to trust that registry, this is done by adding a `"insecure-registries" : ["localhost:32000"]` to the `dockerd.json` file of your host, see https://docs.docker.com/registry/insecure/ . Then you should be able to tag and push to that registry and consume the images from inside MicroK8s.
- Have your host's `docker` talk to the dockerd of MicroK8s. MicroK8s' dockerd is listening on `unix:///var/snap/microk8s/current/docker.sock` so you can use the `-H` parameter like so: `docker -H unix:///var/snap/microk8s/current/docker.sock` while building your image. See: https://github.com/ubuntu/microk8s/blob/master/docs/dockerd.md
- Use `microk8s.docker` to build your image. `microk8s.docker` is already configured to talk to the dockerd packaged inside the snap.
- Finally you could edit the arguments of kubelet in `/var/snap/microk8s/current/args/kubelet` to point to the docker daemon on the host (`--docker` and `--docker-endpoint` arguments). Have't tested this but it should work.

Let me also give you a heads up on the direction we are going so you choose the right approach. In future releases we will not be shipping dockerd with MicroK8s. Instead, we will move to containerd. This practically means the most future proof option is to use the registry addon.

Thank you for using MicroK8s.

**Comment by snowmansora** [comment]
@ktsakalozos 

Thanks for your informative reply!!

I am not that familiar with containerd, but from the sounds of it, I can use my host docker to build the image, tag it under registry "localhost:32000", and push it to containerd right (even though it is built by docker)?

And is there any difference when running that image with containerd when compared to docker?
Asking that because I think most K8s deployments are using docker, and if I am using microK8s to test my pod/image, it would not be ideal if the pod/image runs fine on containerd but not docker (and vice versa).

Thanks!

**Comment by ktsakalozos** [comment]
> I can use my host docker to build the image, tag it under registry "localhost:32000", and push it to containerd right (even though it is built by docker)?

Yes, that's the idea.

> is there any difference when running that image with containerd when compared to docker

There is no difference between running an image with dockerd and containerd. Actually, I think dockerd internally uses containerd.

Based on the evaluation done by the upstream Kubernetes project, dockerd adds some overhead. Running images with containerd should display higher performance, have a look here https://kubernetes.io/blog/2018/05/24/kubernetes-containerd-integration-goes-ga/ .

Cheers

**Comment by snowmansora** [comment]
Thanks for all the information provided!
Good to know about the trend to containerd.

**Comment by lphuberdeau** [comment]
The last method suggesting kubelet to use the host docker install seems to work just fine with few changes.

/var/snap/microk8s/384/args/kubelet
```
--kubeconfig=${SNAP}/configs/kubelet.config
--cert-dir=${SNAP_DATA}
--network-plugin=kubenet
--root-dir=${SNAP_COMMON}/var/lib/kubelet
--docker-root=/var/lib/docker
--fail-swap-on=false
--pod-cidr=10.1.1.0/24
--non-masquerade-cidr=10.152.183.0/24
--cni-bin-dir=${SNAP}/opt/cni/bin/
--docker unix:///run/docker.sock
--docker-endpoint unix:///run/docker.sock
--feature-gates=DevicePlugins=true
--eviction-hard="memory.available<100Mi,nodefs.available<1Gi,imagefs.available<1Gi"
--cluster-domain=cluster.local
--cluster-dns=10.152.183.10

```

**Comment by badeball** [comment]
@lphuberdeau, with your solution, would microk8s still *start* its own daemon, but just not use it?
