### ISSUE TITLE
Unable to complete Zero to JupyterHub with Kubernetes installation

### ISSUE THREAD

**Issue by hickst** [ubuntu/microk8s#354]
A couple (of us) folks were (independently) trying to follow the _Zero to JupyterHub with Kubernetes_ guide today using microk8s when we were stopped by the same problem. One of us filed an issue on the JupyterHub site but respondents weren't very familiar with microk8s and I thought it might be better to ask you'all about it.

The problem report and our attempts to solve it are detailed in this issue filing:
[jhub on microk8s](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1189)

Basically, I can get the Helm installation running, except for one LoadBalancer service (`proxy-public`) which remains in perpetual `<pending>` state.

[The relevant part of the Z2JH Guide is here](https://z2jh.jupyter.org/en/latest/setup-jupyterhub.html#setup-jupyterhub). Note in Step 5, the `service/proxy-public` should eventually get an external IP address, but it hangs on my microk8s installation.

Any thoughts on where I am going wrong would be greatly appreciated.

[inspection-report-20190312_202442.tar.gz](https://github.com/ubuntu/microk8s/files/2959664/inspection-report-20190312_202442.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @hickst 

MicroK8s does not come with a [loadbalancer](https://kubernetes.io/docs/concepts/services-networking/#loadbalancer) so the proxy public service will not get an external IP and will remain `pending`. You can access the service directly through the cluster IP since the machine MicroK8s is running on is a Kubernetes node. You can also set the `proxy-public` to be of type `NodePort`. If I am not mistaken you can set that service type in the `config.yaml` of the "Prepare configuration file" section as you do in the case of minikube https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/minikube-config.yaml#L3 .
