### ISSUE TITLE
random OCI runtime exec failures

### ISSUE THREAD

**Issue by Tombar** [ubuntu/microk8s#359]
Hello

We have been running a development environment with microk8s for 20+ days when suddenly we are seeing pods that were running failing their liveness/readiness probes and deleting them fails to schedule them again, but we are still able to deploy new pods

```
# pod that was running, now failing: 
spec.containers{zookeeper}   Warning   Unhealthy   kubelet, voyager   Readiness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process148393587: no such file or directory: unknown

spec.containers{zookeeper}   Warning   Unhealthy   kubelet, voyager   Liveness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process488646966: no such file or directory: unknown

# simple shell failing to allocate:
Error: failed to start container "my-shell": Error response from daemon: failed to create OCI runtime console socket: stat /run/user/0/snap.microk8s: no such file or directory: unknown
```

Couldn't find any reference online to the issue, could you please share any light? I'm happy to provide more details or information if needed.

Regards

M

[inspection-report-sanitized-20190314_195700.tar.gz](https://github.com/ubuntu/microk8s/files/2968467/inspection-report-sanitized-20190314_195700.tar.gz)

**Comment by Tombar** [comment]
Adding some more context:

* we destroy the current microk8s cluster on the machine & reboot it
* remove snapd completely and rm -rf ~/snapd
* reinstalled snapd and microk8s --classic --edge 
* we were again able to deploy most of our services successfully 

`BUT` we still have some services failing due to the same reasons, strangely enough, some of the service failing are the same as before but not all. 

Is there anything we could try or provide more feedback on?

**Comment by Tombar** [comment]
So, after confirming it was a microk8s issue and finding a similar issue #358 I've tried installing instead of edge `snap install microk8s --classic --channel 1.13/stable` and the system is working again.

Is there any reason why the installed snap would get updated without manual intervention?

**Comment by vincent-pli** [comment]
@Tombar 
1.13/stable still not work for me, I use 1.12/stable fix my issue, thanks

**Comment by ktsakalozos** [comment]
Hi @Tombar 

I do not see what may be causing this. Could you share the yaml manifests you apply or any way I can reproduce this locally?

To your question on snap updates snap updates happen as soon as the snap author releases a new snap revision on the channel you are following. You can specify when you want to accept new revisions so that your workflow does not get affected: https://docs.snapcraft.io/keeping-snaps-up-to-date/7022

Specifically  for MicroK8s, the --edge channel as well as the --<current-k8s-release>/edge (ie right now the --1.13/edge) channels get updated as soon as a pull request passes the tests or there is an upstream patch release (eg v1.13.5 is out while we are on v1.13.4). The --<old-k8s-release>/edge channels (ie --1.12/edge, --1.11/edge...) get only critical fixes so they get updated when there is an upstream K8s release.

All beta and candidate channels pull everything there is on edge upon an upstream Kubernetes patch release. In this way we release to beta and candidate all patches to MicroK8s since the last release that have landed to edge.

The stable channels normally get updated a week after a new release has hit candidate. This one week delay allows us to block any broken K8s releases that where not filtered out by our testing.

Thanks

**Comment by encuentratuheroedigital** [comment]
Hi,
it's happening the same to me. I fixed it installing a different version, but two hours later I started getting the same error: failed to create runc console socket: stat /run/user/0/snap.microk8s: no such file or directory: unknown. 
First I installed 1.12/stable and then 1.13/stable

**Comment by Tombar** [comment]
Hello, our system was working fine for the last 30 days after we moved into `1.13/stable` until today where running pods are again failing to start and we are seeing:

```
  Warning  BackOff    8m (x431 over 1h)  kubelet, voyager  Back-off restarting failed container
  Warning  Unhealthy  3m (x158 over 1h)  kubelet, voyager  (combined from similar events): Readiness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process274900224: no such file or directory: unknown
```

The exact version we are running is `microk8s  v1.13.5  493`, any help would be appreciated

**Comment by Tombar** [comment]
Rolling back to `microk8s  v1.13.4  438` solves the issue inmediately and without any further commands.

**Comment by dlspano** [comment]
I hit this same issue when microk8s auto refreshed to 1.12.7 and rabbitmq deployed via helm. Once I reverted to 1.12.6, everything was working again.

OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process335596214: no such file or directory: unknown

**Comment by fmazoyer** [comment]
Looks like top of stable channel of 1.13 was rolled back to 438.
In your opinion, what's th best way to pin it down and don't budge unless desired?
Thanks a lot for your help and quick moves :)

**Comment by ktsakalozos** [comment]
@fmazoyer there is no way to completely disable the updates. What you can do is to push them forwards in the future in a convenient period.  Read more here: https://docs.snapcraft.io/keeping-snaps-up-to-date/7022
