### ISSUE TITLE
Alternative to snap/squashfs

### ISSUE THREAD

**Issue by brandonros** [ubuntu/microk8s#362]
```
$ sudo snap install microk8s --classic
error: system does not fully support snapd: cannot mount squashfs image using "squashfs": mount:
       unknown filesystem type 'squashfs'
```

OVH (a popular dedicated hosting company) does not have squashfs support on their kernel for their Ubuntu 16.04 image.

Is there an alternative way to acquire microk8s?

**Comment by ktsakalozos** [comment]
Hi @brandonros 

I opened an issue with the snapcraft people: https://forum.snapcraft.io/t/squashfs-alternative/10463 . I am not aware of any alternatives.

**Comment by ktsakalozos** [comment]
@brandonros seems there is an alternative. Cloud you followup with the snap team at   https://forum.snapcraft.io/t/squashfs-alternative/10463 . Thanks

**Comment by chipaca** [comment]
As far as I know, if it's Ubuntu, it supports squashfs. And conversely, if it doesn't support squashfs, it isn't Ubuntu.

**Comment by brandonros** [comment]
I `sudo apt-get install linux-image-generic` and rebooted. I believe that fixed it.

**Comment by misaalanshori** [comment]
Kind of unrelated, but I tried installing microk8s on a vps and it gave me the same error, the cause seems to be my vps which apparently doesn't give access to /mnt which I think means I can't mount anything including squashfs. The vps people told me to install and use squashfuse instead but I already installed squashfuse and now I don't know how to make snap use squashfuse
