### ISSUE TITLE
microk8s.reset blocked somewhere

### ISSUE THREAD

**Issue by shenkejie15** [ubuntu/microk8s#393]
when I run `microk8s.reset`,

> Calling clean_cluster
Cleaning resources in namespace default
endpoints "kubernetes" deleted
.............
.............
.............
destinationrule.networking.istio.io "istio-policy" deleted
destinationrule.networking.istio.io "istio-telemetry" deleted
gateway.networking.istio.io "istio-autogenerated-k8s-ingress" deleted
rolebinding.rbac.authorization.k8s.io "prometheus-system" deleted
role.rbac.authorization.k8s.io "prometheus-system" deleted

then terminal stay here for at least 20 minutes without any change.
so I have to use Ctrl + C to terminate it.

here is the result of microk8s.inspect:
[inspection-report-20190328_190921.tar.gz](https://github.com/ubuntu/microk8s/files/3017611/inspection-report-20190328_190921.tar.gz)

my env: Ubuntu18.04 LTS

**Comment by ktsakalozos** [comment]
The reason I see this from time to time is because the `kubectl delete` command waits for the resources to be freed. So if Kubernetes keeps a container in terminating state the delete command will wait. We may want to use timeouts and/or grace period in https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-reset.wrapper

**Comment by shenkejie15** [comment]
Thanks for reply. I solved the problem by many times of microk8s.reset until it executed to the end. The same problem never occurs again when I reset my microk8s, so I think we can close the issue.

**Comment by foobarbecue** [comment]
I am encountering this problem.
