### ISSUE TITLE
Can't use local images since 1.14

### ISSUE THREAD

**Issue by falsandtru** [ubuntu/microk8s#417]
Since k8s 1.14 we have to use official docker (or another one) instead of microk8s.docker. But microk8s can't find local images made by official docker. How can microk8s use that images? Or a bug?

**Comment by ktsakalozos** [comment]
Hi @falsandtru ,

Images that build locally are not immediately accessible to MicroK8s. You need to either upload them to a registry (`microk8s.enable registry` will setup a private registry), or load them directly to MicroK8s with `microk8s.crt`.

Have a look at https://github.com/ubuntu/microk8s/blob/master/docs/registry.md and  https://github.com/ubuntu/microk8s/issues/382#issuecomment-477174066 to see how you can use the registry. Uploading directly to containerd is discussed here: https://discuss.kubernetes.io/t/microk8s-local-docker-image-workflow-with-containerd/5708/3

**Comment by falsandtru** [comment]
Thanks, I resolved with https://github.com/ubuntu/microk8s/blob/master/docs/registry.md. Can we document `localhost:32000` as a common solution in other places? Or it has no interoperability?

**Comment by rafaelsoaresbr** [comment]
Hi @ktsakalozos 
Do I have to install docker on the same machine that is running microk8s and configure the insecure registry? I am getting this error, didn't installed docker. https://github.com/ubuntu/microk8s/issues/382#issuecomment-481813874

**Comment by odino** [comment]
Please consider providing a fallback to the `docker save $IMAGE` workaround -- it's fairly slow and painful :)

Ideally, we should be able to override docker.io as default registry, and use the one installed by microk8s instead (so that when k8s pulls `image` it actually goes to `localhost:32000/image`, and only fallback to docker.io if the image is not found there). I think another k8s orchestrator (maybe openshift?) has something similar.

Currently, my major pain point is having to update local manifests that I (microk8s) use vs the rest of the team (docker for mac) uses -- whenever I need to hack on something I need to update the image to prefix it with `localhost:32000/`; it's quite painful :slightly_smiling_face:

**Comment by felipecruz91** [comment]
> Thanks, I resolved with https://github.com/ubuntu/microk8s/blob/master/docs/registry.md. Can we document `localhost:32000` as a common solution in other places? Or it has no interoperability?

The URL is broken. Could you update it please?

**Comment by ktsakalozos** [comment]
> The URL is broken. Could you update it please?

The work on registries has been moved at https://microk8s.io/docs/ under `Images and registries`.
