### ISSUE TITLE
Cannot create any new pods

### ISSUE THREAD

**Issue by soapergem** [ubuntu/microk8s#419]
I installed Ubuntu Server 18.04 awhile ago with microk8s selected among the options of software to install. I added a number of extensions using `microk8s.enable` such as istio, registry, and some others. Furthermore I installed Tiller so that I could use Helm to install a number of prepackaged, stable charts. And for a little while everything was working swimmingly. I have a NAS device on my home network so I installed the [NFS Client Provisioner](https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner) Helm chart to make use of it for PersistentVolumeClaims. That, too, was working well for awhile. I later installed the [PostgreSQL](https://github.com/helm/charts/tree/master/stable/postgresql) Helm chart and had that up and running.

However, after about 10 days, I noticed that it said my Postgres pod had restarted... and had not come back up yet. It had gone from a Ready state of `1/1` pods to `0/1`, with a status of `Init`. I've tried to do some troubleshooting: for instance I've tried running `kubectl get events` before and after trying to reinstall the Helm chart. I've tried doing a `kubectl describe pod/xxxxx` for more information about an individual pod coming up. I even tried watching the log stream with [kail](https://github.com/boz/kail), but nothing out of the ordinary appeared there either. At first I thought it was just the Postgres pod, but quickly discovered that in fact, I can no longer create *any* new pods. My `nfs-client-provisioner` pod is the only one still running. But even if I try to do something simple like:

```
kubectl run --restart=Never alpine --image=alpine --command -- tail -f /dev/null
```

It simply gets stuck in the `ContainerCreating` status indefinitely. Literally no new pods can be created, though it gives no error messages or warnings or anything. It appears as if things are about to start at any moment, but then they never do.

I'm prepared to simply reformat and reinstall the whole Ubuntu Server all over again. But before I do, I thought I'd post my issue here in case others have already encountered something similar. I've also attached my results of `microk8s.inspect` here: 
[inspection-report.tar.gz](https://github.com/ubuntu/microk8s/files/3055926/inspection-report.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @soapergem, thank you for reporting this. I cannot find what is off in this deployment, often this behavior is due to firewall settings but I cannot be sure.

I see you are not using MicroK8s as an ephemeral k8s cluster and this may not "play well" with the frequent releases of Kubernetes. Here are some suggestions you may find helpful in increasing the stability of your cluster.

If you do not specify a channel during installation you will be following the latest Kubernetes release. Therefore you should expect some disruption every time there is a Kubernetes upstream release. This disruption may be significant in the case of non-patch releases (eg from 1.13 to 1.14). We are doing our best to keep everything backwards compatible but this is not always possible. To have full control over which k8s release you have running you should deploy MicroK8s with the --channel set, eg:
```
sudo snap install microk8s --classic --channel=1.14/stable
```

In addition, in order to not get any disruption in your workflow you could consider setting exactly the time updates will reach you. Read more at https://docs.snapcraft.io/keeping-snaps-up-to-date/7022

**Comment by soapergem** [comment]
Thanks for the help. I've just reimaged the box and reinstalled MicroK8S with the command you've supplied here. The pods are working again... for now. Hopefully this situation was a unicorn and we don't see it again. In the meantime, I've now encountered a brand new issue which had previously just worked out-of-the-box: #421
