### ISSUE TITLE
microk8s.config fails with more than one network interface

### ISSUE THREAD

**Issue by xordspar0** [ubuntu/microk8s#440]
If the host system has more than one network interface, `microk8s.config` fails with the following error:

```
/snap/microk8s/522/bin/sed: -e expression #1, char 26: unterminated `s' command
```

The problem is that the list of the system's IP addresses contains a newline, which makes an invalid expression in sed.

Here's the relevant portion of the trace of microk8s-config.wrapper:

```sh
++ local 'IP_ADDR=159.65.190.225
10.17.0.5'
++ [[ -z 159.65.190.225
10.17.0.5 ]]
++ echo '159.65.190.225
10.17.0.5'
+ IP_ADDR='159.65.190.225
10.17.0.5'
+ /snap/microk8s/522/bin/sed -e 's/127.0.0.1/159.65.190.225
10.17.0.5/' /var/snap/microk8s/522/credentials/client.config
/snap/microk8s/522/bin/sed: -e expression #1, char 26: unterminated `s' command
```

This is a fresh install of v1.14.1  2019-04-18 (522).

**Comment by xordspar0** [comment]
More precisely, this system has a network interface that has two IP addresses:

```
# ip -o -4 addr list ens3
2: ens3    inet 159.65.190.225/20 brd 159.65.191.255 scope global ens3\       valid_lft forever preferred_lft forever
2: ens3    inet 10.17.0.5/16 brd 10.17.255.255 scope global ens3\       valid_lft forever preferred_lft forever
```

**Comment by ktsakalozos** [comment]
@xordspar0 thank you for reporting this.

I am sure you already figured the workaround:
```
microk8s.config -l
# replace 127.0.0.1 with the the IP of your liking
```

For sure we need to fix the `get_default_ip()` to return a single IP in https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/common/utils.sh#L125

However, I believe the `microk8s.config` command (https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-config.wrapper) should have an option to pass the IP you want the kubeconfig file to be produced for. This is because the API server by default listens on all interfaces so the default IP might not be the one you need. What do you think?
