### ISSUE TITLE
Unable to register node with API server: Node is invalid

### ISSUE THREAD

**Issue by TimJVK** [ubuntu/microk8s#444]
I am in the process of installing microk8s on a server that contains "_" characters in the hostname. Logs indicate that the "_" character cause node creation to fail (see inspection report) Is there a way to work around this by using a alternate name for the node?

Thanks in advance!

[journal.log](https://github.com/ubuntu/microk8s/files/3109237/journal.log)

**Comment by TimJVK** [comment]
Sorry, the underscore character did not resolve in the post above between the "".

**Comment by ktsakalozos** [comment]
Hi @TimJVK 

There is the `--hostname-override` argument of kubelet you could try. 

Edit ` /var/snap/microk8s/current/args/kubelet` and append something like `--hostname-override=new-name`. Then do a `microk8s.stop` followed by a `microk8s.start` to reload the new config.

I wonder if we should be naming the node instead of using the hostname.

**Comment by TimJVK** [comment]
Worked like a charm! Thanks for your help and the quick response!

**Comment by gajen0981** [comment]
thank you! 

I followed this guide to change my hostname so it doesn't have any special characters. I didn't have to override the hostname. 

https://linuxize.com/post/how-to-change-hostname-on-ubuntu-18-04/

**Comment by JonDGH** [comment]
It seems that using --hostname-override in the kubelet config will enable a cluster to start, however it all falls apart after RBAC is enabled.
