### ISSUE TITLE
MicroK8s services restart after a refresh

### ISSUE THREAD

**Issue by ktsakalozos** [ubuntu/microk8s#474]
Due to https://forum.snapcraft.io/t/disabled-snap-gets-enabled-after-a-refresh/7457/8 even if you have done `microk8s.stop` microk8s will start again on a refresh.

If pods remain in the Pending state and your node is shown as `SchedulingDisabled` in `microk8s.kubectl get no`, you will want to do a `microk8s.kubectl uncordon "your_node"`.

**Comment by ktsakalozos** [comment]
It seems we will have to handle this ourselves. When we `microk8s.stop`  we could create a lock file under `/var/snap/microk8s/current/var/lock/`, our daemon wrappers shown here `https://github.com/ubuntu/microk8s/blob/master/snapcraft.yaml#L18`  and found here `https://github.com/ubuntu/microk8s/tree/master/microk8s-resources/wrappers` would need to check that this lock file is not present before starting the daemon. `microk8s.start` would remove the lock-file.

**Comment by captn3m0** [comment]
Is there a workaround for this? Snap upgrades are completely opaque, and it takes me a while to notice that microk8s is running again.

**Comment by bjrne** [comment]
This is still bugging me. Please reopen!

**Comment by ktsakalozos** [comment]
Hi @bjrne , what version of MIcroK8s are you on? Starting with 1.22 the K8s services will restart when refreshing but the workloads should stay untouched.

**Comment by bjrne** [comment]
I am very sorry, I investigated this further and it seems that I missed the `--disable` flag for the `snap stop` command. Since the bug in snap seems to have been fixed, it was probably only my user error that caused microk8s to unwantedly start again.
Sorry again for the confusion, this can probably be closed again. I'll report back in the unlikely case that the problem will appear again.

For everyone else who comes here via google:
`snap stop --disable microk8s` is probably what you're looking for if you want to stop microk8s from starting again after a snap refresh or reboot.

**Comment by ktsakalozos** [comment]
Thank you for investigating this issue @bjrne . `microk8s stop` stops the snap and disables its services [1] exactly as you suggest..

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-stop.wrapper#L42
