### ISSUE TITLE
microk8s.kubectl doesn't work when pwd is in an nfs mount

### ISSUE THREAD

**Issue by muyiscoi** [ubuntu/microk8s#481]
Running microk8s.kubectl in a non-nfs mounted directory works as expected
```
muyiwaiyowu@bespin:~$ microk8s.kubectl get nodes
NAME     STATUS   ROLES    AGE   VERSION
bespin   Ready    <none>   23m   v1.14.1
```
However, when running the same command while in an nfs mounted directory, it displays an error
**NFS mounts on the VM**
```
muyiwaiyowu@bespin:/repos$ mount | grep nfs
192.168.42.1:/home/muyiwaiyowu/git/env on /vagrant type nfs (rw,relatime,vers=3,rsize=32768,wsize=32768,namlen=255,hard,proto=udp,timeo=11,retrans=3,sec=sys,mountaddr=192.168.42.1,mountvers=3,mountport=51595,mountproto=udp,local_lock=none,addr=192.168.42.1)
192.168.42.1:/home/muyiwaiyowu/git on /repos type nfs (rw,relatime,vers=3,rsize=32768,wsize=32768,namlen=255,hard,proto=udp,timeo=11,retrans=3,sec=sys,mountaddr=192.168.42.1,mountvers=3,mountport=51595,mountproto=udp,local_lock=none,addr=192.168.42.1)
```
**Running `microk8s.kubectl`**
```
muyiwaiyowu@bespin:/repos$ microk8s.kubectl get nodes
cannot open path of the current working directory: Permission denied
muyiwaiyowu@bespin:/repos$ cd /vagrant/
muyiwaiyowu@bespin:/vagrant$ microk8s.kubectl get nodes
cannot open path of the current working directory: Permission denied
```
Please let me know if there's any other information needed.
[inspection-report-20190523_153653.tar.gz](https://github.com/ubuntu/microk8s/files/3213034/inspection-report-20190523_153653.tar.gz)

**Comment by muyiscoi** [comment]
Relevant syslog entry

```
May 23 16:02:14 bespin kernel: [  303.596192] nfs: RPC call returned error 13
May 23 16:02:14 bespin kernel: [  303.596318] audit: type=1400 audit(1558627334.667:93): apparmor="DENIED" operation="sendmsg" profile="/snap/core/6964/usr/lib/snapd/snap-confine" pid=8759 comm="snap-confine" lport=767 family="inet" sock_type="dgram" protocol=17 requested_mask="send" denied_mask="send"
```
Based on the log above, I also found this bug on launchpad which seems like it might be related
https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1784499

**Comment by pwaller** [comment]
Hi!

I'm not a user of microk8s, but found this thread by searching for `cannot open path of the current working directory`, which I was encountering.

The error message is actually arising from snap, as it tries to confine minik8s:

https://github.com/snapcore/snapd/blob/347d86f171bb76f0d799e001257059f33f4c14a8/cmd/snap-confine/snap-confine.c#L141

Furthermore, it was happening to me because I was trying to run a snap-based command from a gvfs mount. I observed that the `openat` was failing for any directory below the mount, regardless of permission bits on all components of the path at the mount point or deeper (I had the rx bits).

I didn't get to the root cause of why, but it seems to me to be an issue with snap or the linux kernel.

**Comment by leopd** [comment]
Looks like this might be a relevant bug report for snapd: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1784774
