### ISSUE TITLE
Enabling storage in Travis CI fails due to timing issue

### ISSUE THREAD

**Issue by knkski** [ubuntu/microk8s#490]
I've got a Travis CI job that uses microk8s, and enables storage. The job worked a few times due to an excellent bit of debugging by @ktsakalozos, but started failing consistently a little while after. See https://travis-ci.org/juju-solutions/bundle-kubeflow/jobs/535363654 for an example.

The solution to make it start working again was to move the `sudo systemctl stop docker.service` bit higher up in the script, giving something more time to finish processing. @ktsakalozos, is this something that microk8s can/should work around by e.g. adding a flag to `microk8s.enable` to wait for the API server to come up or something? Otherwise, feel free to mark this ticket as invalid, since the fix is to just move the systemctl command higher up in the script.

**Comment by ktsakalozos** [comment]
Thank you for reporting this @knkski . 

The reason behind this issue is that some not so old versions of docker were using port 10010 for the stream server [1]. The containerd in MicroK8s was also configured is this way. This is addressed [2] in the MicroK8s release on candidate and will reach stable soon. A random available port is used now so there is no danger of clashing. 

I am closing this as it is fixed and (almost) released.

[1] https://github.com/moby/moby/issues/37507
[2] https://github.com/ubuntu/microk8s/commit/38ebe00d8c731e011194c791b12c01c7f573830f#diff-00bf7c5742dac5374d50f08951a6f40dR26
