### ISSUE TITLE
Fluentd, ElasticSearch-Logging

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#502]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

Currently I have fluentd running as a sidecar in every application pod and spin up my own ES cluster. What's the use case of the fluentd add-on and elasticsearch-logging provided by MicroK8s in kube-system namespace? Can it be used as a single point of log proxy / collection from all application pods and shown in Kibana?

**Comment by balchua** [comment]
@khteh having fluentd per pod is very much suitable for multi-tenant kubernetes cluster.  But this adds a couple of disadvantages.  First, you have the overhead of the sidecars.  Second, you don't get all the kubernetes metadata that can be very helpful in debugging both the pod and the cluster.

In our setup, since its an on prem cluster we use node level logging agent, similar to the setup you notice in microk8s.

I hope i was able to explain to you properly.
