### ISSUE TITLE
Add command to facilitate dashboard access

### ISSUE THREAD

**Issue by carmine** [ubuntu/microk8s#584]
`microk8s.enable dashboard` requires me to generate a token and enter it into the browser to access the dashboard. It'd be better/helpful if microk8s is able to automate this for me (possibly as part of the .enable dashboard step, or as a separate command).

**Comment by ktsakalozos** [comment]
Hi @carmine 

Currently `microk8s.enable dashboard` finishes with:
```
If RBAC is not enabled access the dashboard using the default token retrieved with:

token=$(microk8s.kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
microk8s.kubectl -n kube-system describe secret $token

In an RBAC enabled setup (microk8s.enable RBAC) you need to create a user with restricted
permissions as shown in https://github.com/kubernetes/dashboard/wiki/Creating-sample-user
```

In the case where RBAC is not enabled would you prefer to display the token instead of showing you how to get it?

In the case where RBAC is enabled would you prefer to display the credentials of an admin user that has full access to the dashboard?

**Comment by carmine** [comment]
Is there something that can be done to simplify the pattern if accessing from localhost? Or is a token or user still required?

If RBAC isn't enabled, displaying the token seems like an improvement - and being able to fetch the token later as well.
