### ISSUE TITLE
new issue in travis: Insufficient permissions to access MicroK8s

### ISSUE THREAD

**Issue by starpit** [ubuntu/microk8s#633]
our travis builds have been fine, until this morning. now we see this message:

> Insufficient permissions to access MicroK8s

our install script has this, which has not changed in a while, certainly not this morning:

> sudo snap install microk8s --classic

has something changed on your end? if so, what is the last version we can pin before this change was made? or was this a change on travis's side?

of the two suggested changes, the one suggesting a `usermod` and relogin clearly is not applicable to a travis scenario.

**Comment by ktsakalozos** [comment]
@starpit you would have to use sudo then. The 1.14, 1.15 and latest tracks have been updated to require sudo (or users in the microk8s group).

Apologies for this inconvenience. We communicated this change in https://discuss.kubernetes.io/t/explicit-use-of-sudo-in-microk8s-cli/7605 but I see this announcement did not reach you. The tag you should watch for is "microk8s" (https://meta.discourse.org/t/email-notifications-based-on-questions-with-specific-tag/55691)

@tvansteenburgh @ammarn911 this has happen in the past. Some users prefer mailing lists. I know this is not the direction we are heading. I have to admit it is easier to register on a maining list than to create an account on a discourse forum and configure your profile so that you get notifications on a tag.

**Comment by ktsakalozos** [comment]
@starpit you could also use newgrp if neither sudo nor relogin are acceptable. See https://superuser.com/questions/272061/reload-a-linux-users-group-assignments-without-logging-out

**Comment by ashishraman** [comment]
` sudo usermod -a -G microk8s ubuntu ` doesnt work

**Comment by ktsakalozos** [comment]
Hi @ashishraman 

> `sudo usermod -a -G microk8s ubuntu` doesnt work

Which distribution are you on? How does it fail? What is the error message?

**Comment by ashishraman** [comment]
Uh, sorry, its not a microk8s issue but CircleCI issue, `newgrp microk8s` on CircleCI gets stuck and doesn't run subsequent commands.

**Comment by aeneasr** [comment]
Yeah, I too can not for the life of me get 1.14 to work on CircleCI. `usermod` doesn't work because I can not relog and `newgrp` has no effect. Because a lot of downstream commands (helm, ...) rely on microk8s I would really like to avoid adding `sudo` everywhere as a workaround.

**Comment by ktsakalozos** [comment]
@aeneasr `sudo -E` may come in handy. It preserves the env variables.

**Comment by moctarjallo** [comment]
Insufficient permissions to access MicroK8s.
You can either try again with sudo or add the user moctarjallo to the 'microk8s' group:

    sudo usermod -a -G microk8s moctarjallo
    sudo chown -f -R moctarjallo ~/.kube

This is the output i get when i run `microk8s enable kubeflow`

And when i retry it with those 2 commands i still get the same complaining after.

What is the solution?
This is the first time i'm installing kubeflow on my machine and i don't have kubernetes or docker installed.
