### ISSUE TITLE
docker network disappeared

### ISSUE THREAD

**Issue by AntonOfTheWoods** [ubuntu/microk8s#647]
[inspection-report-20190914_065831.tar.gz](https://github.com/ubuntu/microk8s/files/3612059/inspection-report-20190914_065831.tar.gz)

I appear to have a couple of issues:
- The 10/ network has disappeared
- I'm getting the dreaded `microk8s is not running. Use microk8s.inspect for a deeper inspection.` for `microk8s.status` but all the services are running. A `microk8s.start` runs without reporting an error but `microk8s.status` still says it's not running. Any ideas?

**Comment by ktsakalozos** [comment]
@AntonOfTheWoods does this happen in new clusters or only this one?

A quick fix could be to copy the default arguments found in /snap/microk8s/current/default-args to /var/snap/microk8s/current/args.

**Comment by ktsakalozos** [comment]
I see that kubelet is not authorized to reach the apiserver. So probably it is missing the following arguments:
```
--cert-dir=${SNAP_DATA}/certs
--client-ca-file=${SNAP_DATA}/certs/ca.crt
```

You could start by:
```
sudo cp /snap/microk8s/current/default-args/kubelet  /var/snap/microk8s/current/args/
sudo microk8s.stop
sudo microk8s.start
```

**Comment by ktsakalozos** [comment]
@AntonOfTheWoods @khteh I know that your deployments are rather old and you are following the latest/stable track (ie you do not specify a track when you snap install microk8s). The latest/stable track will periodically introduce breaking changes either by upstream kubernetes deprecating features or us the by changing the default configuration. If you intend to keep a deployment for long you would better select a track to follow so you are not affected by unexpected upgrades, eg:
```
sudo snap install microk8s --classic --channel=1.15/stable
```
Please read more at https://microk8s.io/docs/release-channels

Here is what you can do since your deployment got broken:
- Revert (see https://snapcraft.io/docs/getting-started) to a working state with: 
```
sudo snap revert microk8s
```
- Schedule when the next update will reach you: https://snapcraft.io/docs/keeping-snaps-up-to-date
- Refresh your deployment so it follows a track. Eg `sudo snap refresh microk8s --channel 1.13/stable`.

I suggest 1.13 since it does not have the patches that probably broke you.

**Comment by AntonOfTheWoods** [comment]
Hi @ktsakalozos . Actually it was the 1.15.3 update that happened on 2019-09-06 that broke things. I have had some issues in the past with major upgrades but was actually happy to be keeping up to date, so didn't mind. I'm tracking stable, so I'm actually guessing that what happened was that the incompatibility was only introduced in the final update (not moving from 1.14 to 1.15, or 1.15.1 to 1.15.2, etc). I'm also guessing that whatever changed wouldn't have broken an original 1.15 install, so I can't complain! 

Just copying the args didn't work (still no 10/ network) so I'll probably just try and do a complete uninstall/reinstall of microk8s. That will let me validate my install procedure still works, and that I can do it quickly :-).
