### ISSUE TITLE
disable prompt when installing knative addons

### ISSUE THREAD

**Issue by lionelvillard** [ubuntu/microk8s#650]
The Knative addon cannot be installed in a CI/CD pipeline due to this prompt:

```
Enforce mutual TLS authentication (https://bit.ly/2KB4j04) between sidecars? If unsure, choose N. (y/N): 
```

Can this be turned off?

**Comment by ktsakalozos** [comment]
There is not option to pass to the `microk8s.enable istio` command so that you are not prompted for input. You will have to do something like: `echo "y" | microk8s.enable istio`.

Adding an option is not that difficult. The `microk8s.enable` script accepts arguments for every addon you request (https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-enable.wrapper#L39). The linkerd addon is one example where we make use of arguments (https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-linkerd.wrapper). The syntax looks like this:
```
microk8s.enable "linkerd:proxy-auto-inject;tls=optional;skip-outbound-ports=1234,3456"
```

Let me know if anyone is interested in contributing this change before we get to it. Thank you.

**Comment by sakshamkhanna** [comment]
@lionelvillard can you please give more info on how to reproduce this issue

**Comment by lionelvillard** [comment]
here the travis config I was trying: https://travis-ci.org/lionelvillard/knative-examples/jobs/586240984
