### ISSUE TITLE
Failed to enable dashboard when running microk8s inside Multipass

### ISSUE THREAD

**Issue by townsend2010** [ubuntu/microk8s#674]
Hi,

We have a user of Multipass who reported a microk8s error when trying out the Kubeflow via the tutorial at https://ubuntu.com/kubeflow/install.  The Multipass related issue can be found at CanonicalLtd/multipass#1083.

I tried the steps as well and reproduced the issue.  It seems that maybe some configuration step is missing inside the Multipass instance?

Thanks!

**Comment by ktsakalozos** [comment]
Thank you @townsend2010, @ycheng for reporting this. 

The issue is with `microk8s.enable dns dashboard` in a fresh install. The dns addon restarts k8s serves and it needs more time for the cluster to come up. While we wait for the PR with the fix to reach stable, a workaround is to do a `microk8s.enable dns; microk8s.status --wait-ready; microk8s.enable dashboard`.
