### ISSUE TITLE
 cannot validate certificate

### ISSUE THREAD

**Issue by ca-ai** [ubuntu/microk8s#805]
I am using microk8s run kubeflow and whenever i kick off a new wf, i keep getting this cert error on my wf pod

```Get https://192.168.75.8:10250/pods: x509: cannot validate certificate for 192.168.75.8 because it doesn't contain any IP SANs```

Any idea

**Comment by ktsakalozos** [comment]
Could you please attach the tarball created by `microk8s.inspect`? @knkski have you seen similar behavior in the past?

**Comment by ca-ai** [comment]
Attached!

Yes seen it before, also notified @knkski  about it already

[inspection-report-20191115_100632.tar.gz](https://github.com/ubuntu/microk8s/files/3852281/inspection-report-20191115_100632.tar.gz)

**Comment by knkski** [comment]
This should be fixed now, with the default Argo executor for kubeflow getting switched to PNS. For posterity's sake the solution for the kubelet executor is to disable Argo's certificate checking, and then add `--anonymous-auth=true` to `/var/snap/microk8s/current/args/kubelet`, then running `sudo snap restart microk8s.daemon-kubelet`. Closing since this should now be fixed, though feel free to reopen if you run into more issues, @ca-ai
