### ISSUE TITLE
Keep microk8s from starting automatically at boot

### ISSUE THREAD

**Issue by seandjones92** [ubuntu/microk8s#863]
Please run `microk8s.inspect` and attach the generated tarball to this issue.
[inspection-report-20191213_113036.tar.gz](https://github.com/ubuntu/microk8s/files/3962210/inspection-report-20191213_113036.tar.gz)

I have been unable to find a way to accomplish this without disabling the snap altogether. There should be a way to prevent microk8s from starting automatically at boot time. This is useful for the desktop/workstation use case.

I am running microk8s on the edge channel on Ubuntu desktop 19.10

**Comment by seandjones92** [comment]
I may have opened this too soon. It appears that the state of the microk8s cluster persists through reboots. If I'm noting this correctly then feel free to have this closed. 

Thanks!

**Comment by ktsakalozos** [comment]
@seandjones92 `microk8s.stop` will disable the snap [1] and `microk8s.start` will enable it again. Disabling the the snap will stop the MicroK8s services and this will persist across reboots. However, due to a bug describe in https://github.com/ubuntu/microk8s/issues/474 services restart upon a snap update. It should be an easy fix but we haven't got into working on it. Since you are following the edge channel snap upgrades are very frequent so your snap does not stay disabled for a long time.

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-stop.wrapper#L40

**Comment by seandjones92** [comment]
Thanks
