### ISSUE TITLE
raspberry pi 4 - ubuntu - start up problem

### ISSUE THREAD

**Issue by mcapello** [ubuntu/microk8s#910]
Hi,
I just install ubuntu 19.10 on my raspberry pi 4b.
I just need some help. 
When I install microk8s, I can not start a pod, it is pending, and when I try status an error is thown.

This are the commands:
sudo snap install microk8s --classic ==> OK
microk8s.kubectl start ==> OK
microk8s.status  ==> microk8s is not running. Use microk8s.inspect for a deeper inspection.
microk8s.kubectl create deployment nginx --image=nginx  ==> OK, but pod is in pending status

Any ideas ?
thankss

this is my inspect:
[inspection-report-20200113_004202.tar.gz](https://github.com/ubuntu/microk8s/files/4052044/inspection-report-20200113_004202.tar.gz)

**Comment by ktsakalozos** [comment]
Sorry for the late response. Could you try the workaround in https://github.com/ubuntu/microk8s/issues/401#issuecomment-480945986 or install an lts ubuntu?

**Comment by uberknot** [comment]
@ktsakalozos  Can you be more specific as to what the work around is? #401 has to do with ZFS not ubuntu 19.10 on raspberry pi4. Thanks in advance.

**Comment by ktsakalozos** [comment]
If you do a `microk8s.kubect describe node` you should see your node reporting `container runtime status check may not have completed yet, missing node capacity for resources: ephemeral-storage`. On first glance I suspected this was because of the file system being zfs that why I pointed you to that comment. I was wrong. If you do a `journalctl -u snap.microk8s.daemon-kubelet` you will see kubelet complaining about cgroups not set correctly. Could you go over these instructions so you enable cgroups https://microk8s.io/docs/install-alternatives#arm ? Thank you.
