### ISSUE TITLE
Microk8s temporary network failures

### ISSUE THREAD

**Issue by jklaw90** [ubuntu/microk8s#922]
When using docker-compose on the host machine, microk8s(with ingress and dns enabled) seems to have temporary network failures and all services are unreachable a short period.

**Steps:**
* start microk8s 
* enable dns and ingress
* create service and deployment 
* run `sudo iptables -P FORWARD ACCEPT`
* on host machine `run docker-compose up`

**Expected:** Should be able to access microk8s service at any time.
**Actual:** unable to access service for a few minutes.

**Comment by ktsakalozos** [comment]
Hi @jklaw90 

When the network interfaces on the host change, MicroK8s needs to reconfigure and restart its services in order to start (or stop) listening in the new (or removed) networks. This is probably why you see this behavior. An example use case for this behavior is to have kubernetes running while you switch between networks with your laptop. Have a look at https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/apiservice-kicker#L29

A way to stop this from happening is to set for the `--bind-address` to the apiserver. Edit the `/var/snap/microk8s/current/args/apiserver` and add the `--bind-address` based on your needs (see https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ on what this argument is doing). Then restart MicroK8s with `microk8s.stop; microk8s.start`.

**Comment by jklaw90** [comment]
@ktsakalozos Thank you I really appropriate it!
