### ISSUE TITLE
kubernetes-dashboard-certs created with no data

### ISSUE THREAD

**Issue by schoren** [ubuntu/microk8s#950]
I'm following this tutorial: 
https://ubuntu.com/tutorials/install-a-local-kubernetes-with-microk8s#2-deploying-microk8s

So far, I installed the snap, and enable `dns` and `dashboard` addons.

When I try to access the dashboard throw the web browser, I get an error about Invalid Certificate, but not because it's self signed, but because it's absolutely empty.

```
$ microk8s.kubectl describe secret/kubernetes-dashboard-certs -n kube-system

Name:         kubernetes-dashboard-certs
Namespace:    kube-system
Labels:       k8s-app=kubernetes-dashboard
Annotations:  
Type:         Opaque

Data
====
```

[inspection-report-20200206_160734.tar.gz](https://github.com/ubuntu/microk8s/files/4167281/inspection-report-20200206_160734.tar.gz)

Not sure if this is a bug, or I'm doing something wrong in the setup. Thanks

**Comment by ktsakalozos** [comment]
Hi @schoren 

This has been reported in the upstream kubernetes dashboard project and based on discussion at https://github.com/kubernetes/dashboard/issues/4684#issuecomment-567276867 it is like this by design. 

Feel free to reopen this issue if you would like us to further investigate and/or imporve the user experience.

Thanks.
